(() => {
 'use strict';
 const M=OutfitModelV2,N=PlannerNeeds,T=OutfitTravelV2,S=OutfitStorageV2,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
 const labels={top:'上衣',bottom:'下装',dress:'连衣裙',outer:'外套',shoes:'鞋',bag:'包',legwear:'打底袜'},esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const repository=S.createRepository(),renderer=OutfitRendererV2.createRenderer(),motions=OutfitMotionsV2;
 let state=M.createState(),prepared=null,busy=true,category='top',revision=0,dialogRevision=0,opened=null,retry=null,tripDay=0,statusTimer,sceneImage=null,sceneRevision=0,sceneKey=null,sceneLoading=false;
 const role=()=>state.roles[state.character],day=()=>state.trip?.days[tripDay],currentNeed=()=>day()?.need||state.need,preferences=()=>({owned:state.owned,strictOwned:state.strictOwned,excluded:state.excluded,adopted:state.adopted,style:state.style||'character'});
 let panel='clothes',motionId='neutral',motionFrame=null,motionRevision=0,motionTimer,motionLoading=false;
 const panelScroll={clothes:0,wearing:0},shownFrame=()=>motionFrame||prepared;
 const panelScroller=id=>$(id==='clothes'?'#wardrobe-body':'#panel-wearing');
 function switchPanel(next,focus=false){panelScroll[panel]=panelScroller(panel).scrollTop;panel=next;for(const id of ['clothes','wearing']){const selected=id===next,b=$('#tab-'+id);b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1;$('#panel-'+id).hidden=!selected;}panelScroller(next).scrollTop=panelScroll[next];if(focus)$('#tab-'+next).focus();}
 for(const id of ['clothes','wearing']){$('#tab-'+id).onclick=()=>switchPanel(id);$('#tab-'+id).onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();switchPanel(e.key==='Home'?'clothes':e.key==='End'?'wearing':panel==='clothes'?'wearing':'clothes',true);}};}
 function resetMotion(){clearTimeout(motionTimer);motionRevision++;motionId='neutral';motionFrame=null;motionLoading=false;$('#figure').dataset.motion='neutral';$('#motion-note').hidden=true;}
 function renderMotions(){const empty=!!state.trip&&!day()?.outfit,actions=motions.actions(state.character);$('#motion-actions').innerHTML=actions.map(a=>`<button data-motion="${a.id}" aria-label="${a.label}${a.supported?'':'，暂不可用'}" aria-pressed="${a.id===motionId}" aria-disabled="${!a.supported}" ${busy||motionLoading||empty||!a.supported?'disabled':''} ${!a.supported?`title="${esc(a.reason)}" aria-describedby="motion-compatibility"`:''}>${a.label}${a.supported?'':'<small>暂不可用</small>'}</button>`).join('');$('#motion-compatibility').hidden=!actions.some(a=>!a.supported);$('#motion-compatibility').textContent='旧肢体动作暂不兼容单件换装';$$('#motion-actions [data-motion]').forEach(b=>b.onclick=()=>playMotion(b.dataset.motion));}
 async function playMotion(id){if(busy||!prepared)return;const a=motions.actions(state.character).find(a=>a.id===id);if(!a?.supported){$('#motion-note').textContent=a?.reason||'这个动作暂不可用';$('#motion-note').hidden=false;return;}resetMotion();if(id==='neutral'){paint();renderMotions();return;}const mine=motionRevision,base=prepared;motionLoading=true;renderMotions();$('#motion-note').textContent='正在准备动作…';$('#motion-note').hidden=false;setBusy(busy);try{if(id==='blink')await renderer.ensureBlink(base);if(mine!==motionRevision||base!==prepared)return;const p=await motions.frame(base,id);if(mine!==motionRevision||base!==prepared)return;motionId=id;motionFrame=p;$('#figure').dataset.motion=id;$('#motion-note').hidden=true;paint();const finish=()=>{if(mine!==motionRevision)return;if($('#dialog').open){motionTimer=setTimeout(finish,200);return;}resetMotion();paint();renderMotions();};motionTimer=setTimeout(finish,motions.duration(id));}catch(e){if(mine===motionRevision){$('#motion-note').textContent=e.message;$('#motion-note').hidden=false;}}finally{if(mine===motionRevision){motionLoading=false;renderMotions();setBusy(busy);}}}
 function status(s){clearTimeout(statusTimer);$('#status').textContent=s;$('#status').hidden=false;statusTimer=setTimeout(()=>$('#status').hidden=true,6500);}
 try{const s=JSON.parse(localStorage.getItem(S.SESSION)||'null');if(s&&M.CHARACTERS.some(c=>c.id===s.character)&&M.CHARACTERS.every(c=>M.validLocks(c.id,s.roles?.[c.id]?.outfit,s.roles?.[c.id]?.locks))&&M.validNeed(s.need)&&Array.isArray(s.owned)&&Array.isArray(s.excluded)){state={...state,...s,trip:null,tripDrafts:{}};state.owned=state.owned.filter(id=>M.item(id));state.adopted=Array.isArray(s.adopted)?s.adopted.slice(-60):[];state.background=['studio','city','walk','bookshop'].includes(s.background)?s.background:'studio';}}catch(e){/* Keep unreadable records untouched. */}
 function persist(){try{localStorage.setItem(S.SESSION,JSON.stringify(state));}catch(e){status('当前搭配仍在，可下载清单');}}
 const frameCache=new Map();async function frame(character,outfit){const key=character+'|'+M.signature(outfit);if(frameCache.has(key)){const p=frameCache.get(key);frameCache.delete(key);frameCache.set(key,p);return p;}const p=await renderer.compose({character,outfit});frameCache.set(key,p);while(frameCache.size>8)frameCache.delete(frameCache.keys().next().value);return p;}
 function setBusy(value){busy=value;$('#stage').setAttribute('aria-busy',String(value));$('#loading').hidden=!value;for(const s of ['#recommend','#remix','#save','#photo','#library'])$(s).disabled=value||!prepared||motionLoading;for(const b of $$('[data-item],[data-lock],[data-owned]'))b.disabled=value||b.dataset.blocked==='true';for(const b of $$('#background,#lighting,#free,#change-need,#need-summary,#clear-locks,#trip-overview,#edit-day,#exit-trip,#strict-owned,#no-skirts,#no-black,#preferred-style,[data-activity],[data-day],#get-suggestions,#self-build,#regenerate-trip,#trip-duration'))b.disabled=value;$('#photo').disabled=value||!prepared||sceneLoading||motionLoading;for(const b of $$('#motion-actions [data-motion]'))b.disabled=value||motionLoading||b.getAttribute('aria-disabled')==='true'||!!state.trip&&!day()?.outfit;}
 async function apply(next,record=opened,index=tripDay,guard=()=>true){const mine=++revision,input=structuredClone(next);if(input.trip){const d=input.trip.days[index];input.roles[input.character]={...input.roles[input.character],outfit:{...(d.outfit||input.roles[input.character].outfit)},locks:{...d.locks},seen:input.roles[input.character].seen||[]};}retry={next:input,record,index,guard};setBusy(true);try{const o=input.trip?.days[index]?.outfit||input.roles[input.character].outfit;const p=await frame(input.character,o);if(mine!==revision||!guard())return false;state=input;opened=record;tripDay=index;prepared=p;resetMotion();retry=null;$('#retry').hidden=true;render();persist();return true;}catch(e){if(mine===revision&&guard()){status(e.message);$('#retry').hidden=false;}return false;}finally{if(mine===revision){if(!guard()){retry=null;$('#retry').hidden=true;}setBusy(false);}}}
 $('#retry').onclick=()=>retry&&apply(retry.next,retry.record,retry.index,retry.guard);
 function close(){dialogRevision++;$('#dialog').close();}function dialog(title,html){dialogRevision++;$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=html;if(!$('#dialog').open)$('#dialog').showModal();return dialogRevision;}
 $('#close-dialog').onclick=close;$('#dialog').addEventListener('cancel',()=>dialogRevision++);$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog')){const b=e.target.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)close();}});
 const lockIcon=on=>`<svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><rect x="4" y="8" width="12" height="9" rx="2"/><path d="${on?'M6 8V5a4 4 0 0 1 8 0v3':'M6 8V5a4 4 0 0 1 7-2'}"/></svg>`;
 function render(){const c=M.CHARACTERS.find(c=>c.id===state.character),r=role();
  $('#characters').innerHTML=M.CHARACTERS.map(c=>`<button class="character" data-character="${c.id}" aria-pressed="${c.id===state.character}" aria-label="${c.name}"><span class="avatar"><img src="assets/characters/${c.id}/original.png" alt=""></span><span>${c.name}</span></button>`).join('');
  $$('[data-character]').forEach(b=>b.onclick=()=>{close();const next=structuredClone(state);next.tripDrafts=next.tripDrafts||{};if(next.trip)next.tripDrafts[next.character]=next.trip;next.character=b.dataset.character;next.trip=next.tripDrafts[next.character]||null;if(next.trip?.days[0]?.outfit)next.roles[next.character]={...next.roles[next.character],outfit:{...next.trip.days[0].outfit},locks:{...next.trip.days[0].locks},seen:[]};apply(next,null,0);});
  $('#stage-name').textContent=c.name;$('#stage-tone').textContent=c.tone;$('#figure').setAttribute('aria-label',c.name+'，'+M.checklist({character:state.character,outfit:r.outfit}).map(i=>i.name).join('，'));
  const need=currentNeed();$('#change-need').textContent=need?'更改 ↗':'选择 ↗';$('#purpose-title').textContent=need?'今天去'+N.ACTIVITIES.find(a=>a.id===need.activity).label:'今天要做什么？';$('#need-summary').textContent=need?N.summary(need):'用途、季节与出行条件 ⌄';
  $('#trip-bar').hidden=!state.trip;$('#days').innerHTML=(state.trip?.days||[]).map((d,i)=>`<button data-day="${i}" class="${d.outfit?'':'pending'}" aria-pressed="${i===tripDay}">第${i+1}天</button>`).join('');$$('[data-day]').forEach(b=>b.onclick=()=>selectDay(Number(b.dataset.day)));
  $('#day-need').textContent=day()?N.summary(day().need):'';$('#wearing-title').textContent=state.trip?`第${tripDay+1}天的搭配`:'这身搭配';$('#save').textContent=state.trip?'保存行程':'保存搭配';$('#day-empty').hidden=!state.trip||!!day()?.outfit;$('#day-empty').textContent=day()?.reason||'';$('#figure').hidden=!!state.trip&&!day()?.outfit;$('#photo').hidden=!!state.trip&&!day()?.outfit;
  const activeSlots=['top','bottom','dress','outer','shoes','bag'];if(r.outfit.dress||M.item(r.outfit.bottom)?.length==='short')activeSlots.push('legwear');if(!activeSlots.includes(category))category='top';
  $('#categories').innerHTML=activeSlots.map(s=>`<button class="category" data-category="${s}" aria-pressed="${s===category}" ${M.itemsFor(state.character).some(i=>i.slot===s)?'':'disabled'}>${labels[s]}</button>`).join('');$$('[data-category]:not(:disabled)').forEach(b=>b.onclick=()=>{category=b.dataset.category;renderItems();$$('[data-category]').forEach(k=>k.setAttribute('aria-pressed',String(k.dataset.category===category)));});renderItems();
  const locks={...(state.trip?.sharedLocks||{}),...r.locks};$('#wearing').innerHTML=M.SLOTS.filter(s=>r.outfit[s]).map(s=>`<div class="wearing-row"><button class="wearing-name" data-focus="${s}"><small>${labels[s]}</small><span>${M.item(r.outfit[s]).name}</span></button><button class="lock" data-lock="${s}" aria-label="${Object.hasOwn(locks,s)?'解锁':'锁定'}${labels[s]}" aria-pressed="${Object.hasOwn(locks,s)}" ${Object.hasOwn(state.trip?.sharedLocks||{},s)?'disabled data-blocked="true" title="在行程与行李中调整全程复用"':''}>${lockIcon(Object.hasOwn(locks,s))}</button></div>`).join('');
  $$('[data-focus]').forEach(b=>b.onclick=()=>{category=b.dataset.focus;switchPanel('clothes');render();$('#wardrobe-body').scrollTop=0;});$$('[data-lock]').forEach(b=>b.onclick=()=>{if(busy)return;const s=b.dataset.lock;if(Object.hasOwn(r.locks,s))delete r.locks[s];else r.locks[s]=r.outfit[s];r.seen=[];if(day())day().locks={...r.locks};render();persist();});$('#clear-locks').hidden=!Object.keys(r.locks).length;
  $('#strict-owned').checked=state.strictOwned;$('#no-skirts').checked=state.excluded.includes('skirt');$('#no-black').checked=state.excluded.includes('black');$('#preferred-style').innerHTML=N.STYLES.map(s=>`<option value="${s.id}" ${s.id===(state.style||'character')?'selected':''}>${s.label}</option>`).join('');
  const valid=currentNeed()?M.validate(state.character,r.outfit,currentNeed(),preferences()):{valid:true};$('#fit-note').hidden=valid.valid;$('#fit-note').textContent=valid.reasons?.[0]||'';renderMotions();paint();environment();setBusy(busy);
 }
 function renderItems(){const r=role(),slot=category,locks={...(state.trip?.sharedLocks||{}),...r.locks},choices=M.itemsFor(state.character).filter(i=>i.slot===slot);if(['dress','outer','bag','legwear'].includes(slot))choices.unshift(null);
  $('#items').innerHTML=choices.map(i=>{const id=i?.id||null,selected=r.outfit[slot]===id;let blocked=Object.hasOwn(locks,slot)&&locks[slot]!==id;try{M.change(state.character,{...r,locks},slot,id);}catch(e){blocked=true;}
   return `<article class="item-card ${selected?'selected':''}"><button class="item-button" data-item="${id||'none'}" data-blocked="${blocked}" aria-pressed="${selected}" ${blocked||busy?'disabled':''}><span class="item-picture">${i?`<img loading="lazy" src="assets/v2/${state.character}/thumbs/${i.id}.webp" alt="">`:'<span class="no-outer">—</span>'}</span><span class="item-name">${i?i.name:slot==='dress'?'恢复分体装':'不搭'+labels[slot]}</span></button>${i?`<label class="own-label"><input data-owned="${i.id}" type="checkbox" ${state.owned.includes(i.id)?'checked':''}>我有类似</label>`:''}</article>`;
  }).join('');$$('[data-item]').forEach(b=>b.onclick=()=>replace(slot,b.dataset.item==='none'?null:b.dataset.item));$$('[data-owned]').forEach(b=>b.onchange=()=>{state.owned=b.checked?[...new Set([...state.owned,b.dataset.owned])]:state.owned.filter(id=>id!==b.dataset.owned);role().seen=[];persist();});setBusy(busy);
 }
 async function replace(slot,id){if(busy)return;try{const next=structuredClone(state),r=next.roles[next.character],shared=next.trip?.sharedLocks||{};const changed=M.change(next.character,{...r,locks:{...shared,...r.locks}},slot,id);changed.locks={...r.locks};next.roles[next.character]=changed;if(next.trip)next.trip=T.changeDay(next.trip,tripDay,changed.outfit,changed.locks);await apply(next);}catch(e){status(e.message);}}
 $('#free').onclick=()=>{category='top';switchPanel('clothes');render();$('#wardrobe-body').scrollTop=0;};$('#clear-locks').onclick=()=>{role().locks={};role().seen=[];if(day())day().locks={};render();persist();};
 function updatePreferences(){state.strictOwned=$('#strict-owned').checked;state.excluded=[$('#no-skirts').checked?'skirt':null,$('#no-skirts').checked?'dress':null,$('#no-black').checked?'black':null].filter(Boolean);state.style=$('#preferred-style').value;Object.values(state.roles).forEach(r=>r.seen=[]);render();persist();}for(const s of ['#strict-owned','#no-skirts','#no-black','#preferred-style'])$(s).onchange=updatePreferences;
 const opts=(xs,value)=>xs.map(x=>`<option value="${x.id}" ${x.id===value?'selected':''}>${x.label}</option>`).join('');
 function needs(activity,editingDay=false){let n=N.normalizeNeed(editingDay?day().need:state.need||{activity:activity||'class',season:'spring'});if(activity){const a=N.ACTIVITIES.find(a=>a.id===activity);n=N.normalizeNeed({...n,activity,detail:a.details[0].id,walking:a.details[0].walking,days:a.defaultDays||1});}
  function form(){const a=N.ACTIVITIES.find(a=>a.id===n.activity),activities=editingDay?N.ACTIVITIES.filter(a=>!a.trip):N.ACTIVITIES;dialog(editingDay?`第${tripDay+1}天要做什么？`:'今天要做什么？',`<div class="activities">${activities.map(a=>`<button class="activity" data-purpose="${a.id}" aria-pressed="${a.id===n.activity}">${a.label}</button>`).join('')}</div><div class="form-grid"><label class="field">具体安排<select id="detail">${opts(a.details,n.detail)}</select></label><label class="field">季节<select id="season">${opts(N.SEASONS,n.season)}</select></label><label class="field">冷暖<select id="warmth">${opts(N.WARMTH,n.warmth)}</select></label><label class="field">走路<select id="walking">${opts([{id:'few',label:'比较少'},{id:'normal',label:'正常'},{id:'many',label:'比较多'}],n.walking)}</select></label>${a.trip?`<label class="field">天数<select id="duration">${Array.from({length:a.range[1]-a.range[0]+1},(_,i)=>a.range[0]+i).map(v=>`<option ${v===n.days?'selected':''}>${v}</option>`).join('')}</select></label>`:''}</div><div class="dialog-actions"><button id="self-build" class="text-button">自己搭</button><button id="get-suggestions" class="dark-button">${a.trip?'安排逐日搭配':'看搭配建议'}</button></div>`);
   const read=()=>N.normalizeNeed({...n,detail:$('#detail').value,season:$('#season').value,warmth:$('#warmth').value,walking:$('#walking').value,days:$('#duration')?Number($('#duration').value):1});
   $$('[data-purpose]').forEach(b=>b.onclick=()=>{const a=N.ACTIVITIES.find(a=>a.id===b.dataset.purpose);n=N.normalizeNeed({...read(),activity:a.id,detail:a.details[0].id,walking:a.details[0].walking,days:a.defaultDays||1});form();});$('#season').onchange=()=>$('#warmth').value=N.SEASONS.find(s=>s.id===$('#season').value).warmth;$('#detail').onchange=()=>$('#walking').value=a.details.find(d=>d.id===$('#detail').value).walking;
   async function accept(generate){const rev=dialogRevision,guard=()=>rev===dialogRevision,next=structuredClone(state),need=read();if(editingDay){next.trip.days[tripDay].need=need;next.roles[next.character].seen=[];if(!await apply(next,opened,tripDay,guard))return;close();if(generate)suggest();return;}next.need=need;next.roles[next.character].seen=[];const isTrip=N.ACTIVITIES.find(a=>a.id===need.activity).trip;if(isTrip){next.trip=T.create(next.character,need,need.days);if(generate)next.trip=T.generate(next.trip,preferences());else next.trip.days.forEach(d=>{d.outfit={...next.roles[next.character].outfit};d.reason=null;});if(next.trip.days[0].outfit)next.roles[next.character]={...next.roles[next.character],outfit:{...next.trip.days[0].outfit},locks:{},seen:[]};if(!await apply(next,null,0,guard))return;close();if(generate)overview();}else{next.trip=null;if(!await apply(next,null,0,guard))return;close();if(generate)suggest();}}
   $('#get-suggestions').onclick=()=>accept(true);$('#self-build').onclick=()=>accept(false);
  }form();
 }
 $('#change-need').onclick=()=>needs(null,!!state.trip);$('#need-summary').onclick=()=>needs(null,!!state.trip);$('#day-need').onclick=()=>needs(null,true);$('#edit-day').onclick=()=>needs(null,true);
 $('#recommend').onclick=()=>currentNeed()?suggest():needs();$('#remix').onclick=()=>currentNeed()?suggest():needs();
 async function suggest(){if(busy)return;const character=state.character,r=role(),locks={...(state.trip?.sharedLocks||{}),...r.locks},result=state.trip?T.recommendDay(state.trip,tripDay,{...preferences(),seen:r.seen}):M.recommend(character,currentNeed(),{...preferences(),locks,seen:r.seen});if(!result.outfits.length){dialog('搭配建议',`<p class="empty">${esc(result.reason)}</p><div class="dialog-actions">${result.exhausted?'<button id="revisit" class="outline-button">重看已见搭配</button>':''}<button id="browse" class="text-button">自己逛衣橱</button><button id="adjust" class="dark-button">调整条件</button></div>`);$('#browse').onclick=close;$('#adjust').onclick=()=>needs(null,!!state.trip);$('#revisit')?.addEventListener('click',()=>{r.seen=[];suggest();});return;}
  const rev=dialog('搭配建议',`<div class="recommendations">${result.outfits.map((o,i)=>`<article class="suggestion"><canvas id="candidate-${i}" width="320" height="480"></canvas><div class="suggestion-foot"><p>${['top','bottom','dress','outer','shoes'].filter(s=>o[s]!==r.outfit[s]).map(s=>labels[s]).join(' · ')||'保留主体搭配'}</p><button data-try="${i}" disabled>试穿 ↗</button></div></article>`).join('')}</div><div class="dialog-actions"><button class="text-button" id="browse">自己逛衣橱</button><button class="outline-button" id="next-suggestions">再换一批 ↻</button></div>`);r.seen=[...new Set([...r.seen,...result.outfits.map(M.signature)])];persist();$('#browse').onclick=close;$('#next-suggestions').onclick=suggest;
  await Promise.all(result.outfits.map(async(o,i)=>{try{const p=await frame(character,o);if(rev!==dialogRevision||state.character!==character)return;renderer.draw($('#candidate-'+i),p);const b=$(`[data-try="${i}"]`);b.disabled=false;b.onclick=async()=>{if(busy)return;try{let next=M.tryOn(state,character,o);next.roles[character].outfit={...o};if(!o.dress)next.roles[character].lastSplit={top:o.top,bottom:o.bottom};if(next.trip)next.trip=T.changeDay(next.trip,tripDay,o,next.roles[character].locks);close();await apply(next);}catch(e){status(e.message);}};}catch(e){if(rev!==dialogRevision)return;const b=$(`[data-try="${i}"]`);b.disabled=false;b.textContent='加载失败，重试';b.onclick=()=>{r.seen=r.seen.filter(k=>k!==M.signature(o));suggest();};}}));
 }
 async function selectDay(i){if(!state.trip?.days[i])return;close();const next=structuredClone(state),d=next.trip.days[i];if(d.outfit)next.roles[next.character]={...next.roles[next.character],outfit:{...d.outfit},locks:{...d.locks},seen:[]};await apply(next,opened,i);}
 $('#exit-trip').onclick=()=>{const next=structuredClone(state);next.tripDrafts=next.tripDrafts||{};next.tripDrafts[next.character]=next.trip;next.need=currentNeed();next.trip=null;apply(next,null,0);};$('#trip-overview').onclick=overview;
 async function overview(){if(!state.trip)return;const t=state.trip,rev=dialog('逐日搭配',`<div class="trip-settings"><label>天数 <select id="trip-duration">${Array.from({length:7},(_,i)=>`<option ${i+1===t.days.length?'selected':''}>${i+1}</option>`).join('')}</select></label><label><input type="checkbox" id="light-packing" ${t.lightPacking?'checked':''}>尽量少带</label></div><div class="trip-grid">${t.days.map((d,i)=>`<article class="trip-card"><canvas id="trip-frame-${i}" width="240" height="360"></canvas><h3>第${i+1}天 · ${N.ACTIVITIES.find(a=>a.id===d.need.activity).label}</h3><p>${d.outfit?esc(N.summary(d.need)):esc(d.reason)}</p><button class="text-button" data-edit-trip="${i}">调整这一天 ↗</button></article>`).join('')}</div><details><summary>全程复用 / 不复用 ⌄</summary><div class="trip-reuse">${M.checklist({character:state.character,outfit:role().outfit}).map(i=>`<div><span>${i.name}</span><label><input type="checkbox" data-shared="${i.slot}" data-id="${i.id}" ${t.sharedLocks[i.slot]===i.id?'checked':''}>全程复用</label><label><input type="checkbox" data-no-reuse="${i.id}" ${t.noReuseItems.includes(i.id)?'checked':''}>这件不复用</label></div>`).join('')}</div></details><div class="dialog-actions"><button id="regenerate-trip" class="outline-button">重新安排整趟</button><button id="packing" class="dark-button">看行李清单 ↗</button></div>`);
  $('#trip-duration').onchange=async()=>{const next=structuredClone(state);next.trip=T.resize(next.trip,Number($('#trip-duration').value));next.trip=T.generate(next.trip,preferences());const index=Math.min(tripDay,next.trip.days.length-1);if(next.trip.days[index].outfit)next.roles[next.character]={...next.roles[next.character],outfit:{...next.trip.days[index].outfit},locks:{...next.trip.days[index].locks},seen:[]};if(await apply(next,opened,index,()=>rev===dialogRevision)&&rev===dialogRevision)overview();};$('#light-packing').onchange=()=>{state.trip.lightPacking=$('#light-packing').checked;persist();};
  async function reviseTrip(change){const next=structuredClone(state);change(next.trip);next.trip=T.generate(next.trip,preferences());const d=next.trip.days[tripDay];if(d.outfit)next.roles[next.character]={...next.roles[next.character],outfit:{...d.outfit},locks:{...d.locks},seen:[]};if(await apply(next,opened,tripDay,()=>rev===dialogRevision)&&rev===dialogRevision)overview();}$$('[data-shared]').forEach(b=>b.onchange=()=>reviseTrip(t=>{if(b.checked)t.sharedLocks[b.dataset.shared]=b.dataset.id;else delete t.sharedLocks[b.dataset.shared];}));$$('[data-no-reuse]').forEach(b=>b.onchange=()=>reviseTrip(t=>{t.noReuseItems=b.checked?[...new Set([...t.noReuseItems,b.dataset.noReuse])]:t.noReuseItems.filter(id=>id!==b.dataset.noReuse);}));$$('[data-edit-trip]').forEach(b=>b.onclick=()=>selectDay(Number(b.dataset.editTrip)));
  $('#regenerate-trip').onclick=async()=>{const next=structuredClone(state);next.trip=T.generate(next.trip,preferences());const d=next.trip.days[tripDay];if(d.outfit)next.roles[next.character]={...next.roles[next.character],outfit:{...d.outfit},locks:{...d.locks},seen:[]};if(await apply(next,opened,tripDay,()=>rev===dialogRevision)&&rev===dialogRevision)overview();};$('#packing').onclick=packing;
  await Promise.all(t.days.map(async(d,i)=>{if(!d.outfit)return;try{const p=await frame(t.character,d.outfit);if(rev===dialogRevision)renderer.draw($('#trip-frame-'+i),p);}catch(e){if(rev===dialogRevision)$('#trip-frame-'+i).setAttribute('aria-label','加载失败，回到这一天重试');}}));
 }
 function packing(){const rows=T.packing(state.trip),pending=state.trip.days.filter(d=>!d.outfit);dialog('行李清单',`${pending.length?`<p class="menu-error">第${pending.map(d=>d.day).join('、')}天还没搭好，清单只包含已安排的日子。</p>`:''}<p class="muted">${rows.length}款 · ${rows.reduce((s,r)=>s+r.packedCount,0)}件装进行李</p><div>${rows.map(r=>`<div class="packing-row"><div>${r.name}<small>${r.color} · 第${r.days.join('、')}天</small></div><input type="number" min="1" max="20" data-quantity="${r.itemId}" value="${r.count}" aria-label="${r.name}数量"><span>${r.worn?'首日穿1件 · ':''}装${r.packedCount}件</span></div>`).join('')}</div><div class="dialog-actions"><button id="back-trip" class="text-button">返回行程</button><button id="copy-packing" class="outline-button">下载清单</button><button id="save-trip" class="dark-button">保存行程</button></div>`);$$('[data-quantity]').forEach(b=>b.onchange=()=>{const n=Number(b.value);if(!Number.isInteger(n)||n<1||n>20){status('数量请选择1—20');b.value=state.trip.quantities[b.dataset.quantity]||1;return;}state.trip.quantities[b.dataset.quantity]=n;persist();packing();});$('#back-trip').onclick=overview;$('#copy-packing').onclick=()=>downloadText(record('旅行清单'));$('#save-trip').onclick=save;
 }
 function record(name,id=crypto.randomUUID()){const r=state.trip?M.recordTrip(state,state.trip,{id,name}):M.record(state,{id,name});if(!state.trip&&motionId!=='neutral')r.motion=motionId;return r;}
 function listHTML(r){if(r.kind==='trip')return `<p class="muted">${r.trip.days.length}天 · ${T.packing(r.trip).length}款衣物</p>${T.packing(r.trip).map(i=>`<div class="checklist-row"><div>${i.name}<small>第${i.days.join('、')}天 · ${i.color}</small></div><span>装${i.packedCount}件</span></div>`).join('')}`;return `<div class="checklist">${M.checklist(r).map(i=>`<div class="checklist-row"><div>${i.name}<small>${i.color}${state.owned.includes(i.id)?' · 我有类似':''}</small></div><button class="alt-button" data-alt="${i.slot}">换一件 ↗</button></div>`).join('')}</div>`;}
 function download(content,name,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(content instanceof Blob?content:new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);}
 function downloadText(r){let lines=[r.name,M.CHARACTERS.find(c=>c.id===r.character).name,r.need?N.summary(r.need):'自由搭配'];if(r.kind==='trip'){for(const d of r.trip.days)lines.push('',`第${d.day}天 · ${N.summary(d.need)}`,d.outfit?M.checklist({character:r.character,outfit:d.outfit}).map(i=>`${i.name}（${i.color}）`).join('、'):d.reason);lines.push('','行李清单（已扣除首日穿在身上的1件）',...T.packing(r.trip).map(i=>`□ ${i.name}（${i.color}）×${i.packedCount} / 共${i.count}件 / 第${i.days.join('、')}天`));}else lines.push(...M.checklist(r).map(i=>`□ ${i.name}（${i.color}）${state.owned.includes(i.id)?' · 我有类似':''}`));download(lines.join('\n'),'穿搭清单.txt');}
 function bindAlternatives(){ $$('[data-alt]').forEach(b=>b.onclick=()=>{const slot=b.dataset.alt,r=role(),locks={...(state.trip?.sharedLocks||{}),...r.locks};const choices=M.itemsFor(state.character).filter(i=>i.slot===slot&&i.id!==r.outfit[slot]).filter(i=>{try{M.change(state.character,{...r,locks},slot,i.id);return true;}catch(e){return false;}}).slice(0,2);dialog('换一件'+labels[slot],choices.length?`<div class="items">${choices.map(i=>`<button class="item-button" data-alternative="${i.id}"><span class="item-picture"><img src="assets/v2/${state.character}/thumbs/${i.id}.webp" alt=""></span><span class="item-name">${i.name}</span></button>`).join('')}</div>`:'<p class="empty">当前锁定下没有可替代的单品。</p>');$$('[data-alternative]').forEach(k=>k.onclick=async()=>{close();await replace(slot,k.dataset.alternative);});});}
 function save(){if(busy||!prepared)return;const old=opened,defaultName=old?.name||(state.trip?`${state.trip.days.length}天旅行`:state.need?N.ACTIVITIES.find(a=>a.id===state.need.activity).label+'搭配':'自由搭配'),snapshot=record(defaultName),savedFrame=shownFrame(),rev=dialog(state.trip?'保存行程':'保存搭配',`<label class="field">名称<input id="plan-name" class="plan-input" aria-label="搭配名称" maxlength="40" value="${esc(defaultName)}"></label>${listHTML(snapshot)}<p id="save-error" class="menu-error" hidden></p><div class="dialog-actions"><button id="download-list" class="text-button">下载清单</button><button id="export-record" class="text-button">导出方案</button>${old?'<button id="save-as" class="outline-button">另存一套</button>':''}<button id="confirm-save" class="dark-button">${old?'更新此方案':'确认保存'}</button></div>`);bindAlternatives();$('#download-list').onclick=()=>downloadText({...snapshot,name:$('#plan-name').value||defaultName});$('#export-record').onclick=()=>download(JSON.stringify({...snapshot,name:$('#plan-name').value||defaultName},null,2),'穿搭方案.json','application/json');
  async function write(overwrite){const r={...snapshot,name:$('#plan-name').value.trim()||defaultName,id:overwrite?old.id:snapshot.id};if(overwrite)r.createdAt=old.createdAt;const thumbnail=document.createElement('canvas');thumbnail.width=240;thumbnail.height=360;renderer.draw(thumbnail,savedFrame);r.thumbnail=thumbnail.toDataURL('image/webp',.8);$$('#confirm-save,#save-as').forEach(b=>b.disabled=true);try{await repository.save(r,{overwrite});if(rev!==dialogRevision){status('方案已保存，在我的搭配中打开');return;}opened=r;dialog('已保存',`<p class="muted">${esc(r.name)}</p>${listHTML(r)}<div class="dialog-actions"><button id="saved-list" class="outline-button">下载清单</button><button id="continue" class="outline-button">继续调整</button>${r.kind==='outfit'?'<button id="wear-today" class="dark-button">今天就穿这套</button>':''}</div>`);bindAlternatives();$('#saved-list').onclick=()=>downloadText(r);$('#continue').onclick=close;$('#wear-today')?.addEventListener('click',()=>{state=M.adopt(state,state.character,role().outfit);persist();close();status('已记下这套，下一次优先看看其他搭法');});}catch(e){if(rev!==dialogRevision){status('未保存，当前搭配仍在');return;}$('#save-error').hidden=false;$('#save-error').textContent=e.message||'保存失败，可下载清单';$$('#confirm-save,#save-as').forEach(b=>b.disabled=false);}}
  $('#confirm-save').onclick=()=>write(!!old);$('#save-as')?.addEventListener('click',()=>write(false));
 }
 $('#save').onclick=save;$('#library').onclick=async()=>{const rev=dialog('我的搭配','<p class="empty">正在打开…</p>');try{const records=await repository.list();if(rev!==dialogRevision)return;$('#dialog-body').innerHTML=records.length?`<div class="saved-grid">${records.map(r=>{const valid=M.validateRecord(r);return `<article class="saved-card">${valid.valid&&typeof r.thumbnail==='string'&&r.thumbnail.startsWith('data:image/webp;base64,')?`<img src="${esc(r.thumbnail)}" alt="${esc(r.name)}">`:''}<div class="saved-card-content"><h3>${esc(r.name||'未识别方案')}</h3><p>${esc(M.CHARACTERS.find(c=>c.id===r.character)?.name||'')}${r.kind==='trip'?' · '+r.trip?.days?.length+'天旅行':''}</p>${valid.valid?`<button class="text-button" data-reopen="${esc(r.id)}">继续调整 ↗</button>`:`<p>${esc(valid.error)}</p><button class="text-button" data-export="${esc(r.id)}">导出原记录</button>`}</div></article>`;}).join('')}</div>`:'<p class="empty">保存一身喜欢的搭配，下次接着搭。</p>';$$('[data-reopen]').forEach(b=>b.onclick=async()=>{const r=records.find(r=>r.id===b.dataset.reopen),next=M.restore(state,r);close();if(await apply(next,r,0)&&r.kind==='outfit'&&r.motion){if(motions.actions(r.character).some(a=>a.id===r.motion&&a.supported))await playMotion(r.motion);else status('已恢复穿搭，该记录的动作暂不兼容');}});$$('[data-export]').forEach(b=>b.onclick=()=>download(JSON.stringify(records.find(r=>r.id===b.dataset.export),null,2),'原方案.json','application/json'));}catch(e){if(rev===dialogRevision)$('#dialog-body').innerHTML='<p class="empty">'+esc(e.message)+'</p>';}};
 function paint(blink=false){if(prepared)renderer.draw($('#figure'),shownFrame(),{blink:!motionFrame&&blink===true});}new ResizeObserver(paint).observe($('#figure'));
 const backgrounds=[{id:'studio',name:'摄影棚'},{id:'city',name:'城市街角'},{id:'bookshop',name:'书店'},{id:'walk',name:'林间散步'}];
 function environment(){const b=backgrounds.find(b=>b.id===state.background)||backgrounds[0];$('#background').textContent=b.name+' ⌄';$('#lighting').hidden=b.id!=='studio';$('#stage').dataset.background=b.id;$('#stage').dataset.light=b.id==='studio'?state.light:'neutral';if(sceneKey===b.id)return;sceneKey=b.id;const mine=++sceneRevision;if(b.id==='studio'){$('#scene').hidden=true;sceneImage=null;sceneLoading=false;setBusy(busy);return;}sceneImage=null;sceneLoading=true;$('#scene').hidden=true;setBusy(busy);const image=new Image();image.onload=()=>{if(mine!==sceneRevision)return;sceneImage=image;sceneLoading=false;$('#scene').src=image.src;$('#scene').hidden=false;setBusy(busy);};image.onerror=()=>{if(mine===sceneRevision){state.background='studio';environment();persist();status('背景暂未加载，已保留摄影棚');}};image.src='assets/scenes/'+b.id+'.webp';}
 $('#background').onclick=()=>{dialog('背景',`<div class="backgrounds">${backgrounds.map(b=>`<button class="background-choice" data-background="${b.id}">${b.id==='studio'?'<span class="studio-swatch"></span>':`<img src="assets/scenes/${b.id}.webp" alt="">`}<span>${b.name}</span></button>`).join('')}</div>`);$$('#dialog [data-background]').forEach(b=>b.onclick=()=>{state.background=b.dataset.background;environment();persist();close();});};$('#lighting').onclick=()=>{dialog('摄影棚光线','<div class="lights"><button data-light="neutral">自然光</button><button data-light="warm">暖光</button><button data-light="cool">柔冷光</button></div>');$$('#dialog [data-light]').forEach(b=>b.onclick=()=>{state.light=b.dataset.light;environment();persist();close();});};
 $('#photo').onclick=()=>{if(busy||!prepared||state.background!=='studio'&&!sceneImage)return;const c=document.createElement('canvas');c.width=900;c.height=1200;const x=c.getContext('2d');if(sceneImage){const s=Math.max(c.width/sceneImage.width,c.height/sceneImage.height);x.drawImage(sceneImage,(c.width-sceneImage.width*s)/2,(c.height-sceneImage.height*s)/2,sceneImage.width*s,sceneImage.height*s);}else{const colors=state.light==='warm'?['#fff5df','#c9b69c']:state.light==='cool'?['#edf5fa','#b7c6cf']:['#f5f2eb','#dedbd4'],g=x.createRadialGradient(450,350,50,450,450,950);g.addColorStop(0,colors[0]);g.addColorStop(1,colors[1]);x.fillStyle=g;x.fillRect(0,0,900,1200);}x.fillStyle='#756b5830';x.beginPath();x.ellipse(450,1125,135,17,0,0,Math.PI*2);x.fill();x.filter=state.background==='studio'?(state.light==='warm'?'sepia(.10) saturate(.96)':state.light==='cool'?'saturate(.91)':'none'):'saturate(.97)';x.drawImage(shownFrame().figure,90,60,720,1080);const url=c.toDataURL('image/png');dialog('拍一张',`<img class="result-photo" src="${url}" alt="无字穿搭照片"><div class="dialog-actions"><button id="photo-download" class="outline-button">下载照片</button><button id="photo-save-plan" class="dark-button">保存这身搭配</button></div>`);$('#photo-download').onclick=()=>c.toBlob(blob=>blob&&download(blob,'今天怎么穿.png'),'image/png');$('#photo-save-plan').onclick=save;};
 function idleBlink(){setTimeout(()=>{if(!busy&&!motionFrame&&!motionLoading&&prepared&&!document.hidden&&!$('#dialog').open&&!matchMedia('(prefers-reduced-motion: reduce)').matches){paint(true);setTimeout(()=>paint(),140);}idleBlink();},5200+Math.random()*1400);}idleBlink();
 render();apply(state,null,0);
})();
