(function(root,factory){const api=factory(typeof module==='object'?require('./model-v2.js'):root.OutfitModelV2,typeof module==='object'?require('./data/needs.js'):root.PlannerNeeds);if(typeof module==='object')module.exports=api;else root.OutfitTravelV2=api;})(globalThis,function(M,N){
 'use strict';
 function count(n){if(!Number.isInteger(n)||n<1||n>7)throw Error('旅行请选择1—7天');}
 function dayNeed(need){const n=N.normalizeNeed(need);return N.normalizeNeed({...n,activity:'sightseeing',detail:['city','beach','park'].includes(n.destination)?n.destination:'city',days:1});}
 function create(character,need,n){count(n);if(!M.CHARACTERS.some(c=>c.id===character))throw Error('请选择人物');return {character,baseNeed:N.normalizeNeed(need),days:Array.from({length:n},(_,i)=>({day:i+1,need:dayNeed(need),outfit:null,locks:{},reason:'还未安排'})),sharedLocks:{},noReuseItems:[],quantities:{},lightPacking:true};}
 function resize(trip,n){count(n);const t=structuredClone(trip);t.days=Array.from({length:n},(_,i)=>t.days[i]||{day:i+1,need:dayNeed(t.baseNeed),outfit:null,locks:{},reason:'还未安排'});return t;}
 function generate(trip,preferences={}){const t=structuredClone(trip),used=new Set(),seen=[];for(const [index,day]of t.days.entries()){const locks={...t.sharedLocks,...day.locks},conflict=Object.entries(t.sharedLocks).some(([s,id])=>Object.hasOwn(day.locks,s)&&day.locks[s]!==id),reserved=(t.noReuseItems||[]).filter(id=>t.days.some((d,i)=>i>index&&Object.values(d.locks).includes(id))),excluded=[...(preferences.excluded||[]),...(t.noReuseItems||[]).filter(id=>used.has(id)),...reserved];
   const result=conflict?{outfits:[],reason:'当日锁定与全程复用项冲突'}:M.recommend(t.character,day.need,{...preferences,locks,excluded,limit:50});
   const score=o=>Object.values(o).filter(Boolean).reduce((sum,id)=>sum+(used.has(id)?(t.lightPacking?10:1):0),0)-(seen.includes(M.signature(o))?80:0);
   const chosen=result.outfits.slice().sort((a,b)=>score(b)-score(a))[0]||null;day.outfit=chosen;day.reason=chosen?null:result.reason||'这天暂无适合搭配';if(!chosen&&t.noReuseItems.some(id=>used.has(id)))day.reason='不复用项与锁定或出行条件冲突，可调整这一天';if(chosen){Object.values(chosen).filter(Boolean).forEach(id=>used.add(id));seen.push(M.signature(chosen));}
  }return t;}
 function recommendDay(trip,index,preferences={}){const d=trip.days[index];if(!d)throw Error('这一天不存在');if(Object.entries(trip.sharedLocks).some(([s,id])=>Object.hasOwn(d.locks,s)&&d.locks[s]!==id))return {outfits:[],reason:'当日锁定与全程复用项冲突',exhausted:false};const excluded=[...(preferences.excluded||[]),...(trip.noReuseItems||[]).filter(id=>trip.days.some((other,i)=>i!==index&&(Object.values(other.outfit||{}).includes(id)||Object.values(other.locks||{}).includes(id))))];return M.recommend(trip.character,d.need,{...preferences,excluded,locks:{...trip.sharedLocks,...d.locks}});}
 function changeDay(trip,index,outfit,locks){if(!trip.days[index])throw Error('这一天不存在');const v=M.visualValidate(trip.character,outfit);if(!v.valid)throw Error(v.reasons.join('；'));for(const [s,id]of Object.entries({...trip.sharedLocks,...(locks||trip.days[index].locks)}))if(outfit[s]!==id)throw Error('请先解锁，再调整这件单品');for(const id of trip.noReuseItems||[])if(Object.values(outfit).includes(id)&&trip.days.some((d,i)=>i!==index&&Object.values(d.outfit||{}).includes(id)))throw Error('这件已设为不复用，请换一件或调整限制');const t=structuredClone(trip);t.days[index].outfit={...outfit};if(locks)t.days[index].locks={...locks};t.days[index].reason=null;return t;}
 function packing(trip){const rows=new Map(),worn=new Set(Object.values(trip.days[0]?.outfit||{}).filter(Boolean));for(const day of trip.days)for(const id of Object.values(day.outfit||{}).filter(Boolean)){if(!M.item(id))continue;if(!rows.has(id))rows.set(id,{...M.item(id),itemId:id,days:[],worn:worn.has(id)});const row=rows.get(id);if(!row.days.includes(day.day))row.days.push(day.day);}
  return [...rows.values()].map(r=>{const n=trip.quantities[r.itemId],count=Number.isInteger(n)&&n>=1&&n<=20?n:1;return {...r,count,packedCount:count-(r.worn?1:0)};}).sort((a,b)=>M.SLOTS.indexOf(a.slot)-M.SLOTS.indexOf(b.slot)||a.days[0]-b.days[0]);}
 return {create,resize,generate,changeDay,packing,recommendDay};
});
