const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{spawn}=require('node:child_process');
const {createCanvas,loadImage}=require('@napi-rs/canvas'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),out=path.join(root,'output/guidance-blink-review'),C=require('../catalog-v2.js'),R=require('../renderer-v2.js');
const renderer=R.createRenderer({createCanvas,loadImage:f=>loadImage(path.join(root,f))});
async function server(){const p=spawn('python3',['-u','serve.py','--port','0'],{cwd:root});const port=await new Promise((ok,no)=>{p.stdout.on('data',b=>{const m=String(b).match(/port (\d+)/);if(m)ok(m[1]);});p.on('error',no);});return {p,url:`http://127.0.0.1:${port}/index.html`};}
const idle=p=>p.waitForFunction(()=>document.querySelector('#stage').getAttribute('aria-busy')==='false'&&!document.querySelector('#save').disabled);
test('local light preserves character alpha, the original face registration and all garment metadata',async()=>{
 const results=[];for(const character of ['sweet','cool','literary']){
  const outfit=C.defaultOutfit(character),prepared=await renderer.compose({character,outfit}),before=Buffer.from(prepared.figure.getContext('2d').getImageData(0,0,1024,1536).data);assert.equal(renderer.illuminate(prepared),prepared);
  for(const light of ['warm','cool']){const lit=renderer.illuminate(prepared,light),after=lit.figure.getContext('2d').getImageData(0,0,1024,1536).data;assert.equal(renderer.illuminate(prepared,light),lit);assert.deepEqual(lit.outfit,outfit);assert.equal(lit.character,character);let changed=0,alpha=0,head=0,body=0;for(let i=0;i<before.length;i+=4){if(before[i+3]!==after[i+3])alpha++;if([0,1,2].some(k=>before[i+k]!==after[i+k])){changed++;if(i<1024*470*4)head++;else body++;}}assert.equal(alpha,0,'transparent edges and face silhouette must remain identical');assert.ok(head>3000&&body>3000);assert.deepEqual(Buffer.from(prepared.figure.getContext('2d').getImageData(0,0,1024,1536).data),before);results.push({character,light,changed,alpha,head,body});}
 }
 fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'local-light-registration.json'),JSON.stringify(results,null,2));
});
test('three supported expressions per role stay local across outfits; native facial sources cannot replace clothes',async()=>{
 const s=await server(),b=await chromium.launch({headless:true});try{const p=await b.newPage({reducedMotion:'reduce'});await p.goto(s.url);await idle(p);const results=await p.evaluate(async()=>{
  const r=OutfitRendererV2.createRenderer(),M=OutfitModelV2,masks={cool:{brow:[[574,234,70,30]],smirk:[[516,366,52,25]]},literary:{focus:[[431,320,62,48],[556,306,62,46]],knowing:[[501,400,56,27]]}},rows=[];
  for(const character of ['sweet','cool','literary']){const base=M.defaultOutfit(character),outfits=character==='cool'?M.looksFor(character).filter(l=>['spring-a','summer-a','winter-b'].some(k=>l.id.endsWith(k))).map(l=>l.outfit):[base,{...base,top:'shared-top-04',bottom:'shared-bottom-01',dress:null,shoes:'shared-shoes-04'},{...base,outer:character==='sweet'?'sweet-outer-01':'literary-outer-02'}];
   const actions=OutfitMotionsV2.actions(character).filter(a=>a.supported&&a.id!=='neutral');if(actions.length<3)throw Error(character+' has fewer than three facial actions');
   for(const outfit of outfits){const prepared=await r.compose({character,outfit}),original=prepared.figure.getContext('2d').getImageData(0,0,1024,1536).data;for(const action of actions){const frame=await OutfitMotionsV2.frame(prepared,action.id),pixels=frame.figure.getContext('2d').getImageData(0,0,1024,1536).data;let changed=0,outside=0;for(let y=0;y<1536;y++)for(let x=0;x<1024;x++){const k=(y*1024+x)*4;if([0,1,2,3].some(i=>pixels[k+i]!==original[k+i])){changed++;const areas=masks[character]?.[action.id];if(areas?!areas.some(([cx,cy,rx,ry])=>((x-cx)/(rx+1))**2+((y-cy)/(ry+1))**2<=1.02):y>=(character==='cool'?435:470))outside++;}}rows.push({character,action:action.id,changed,outside});}}
  }return rows;
 });assert.equal(results.length,27);for(const row of results){assert.ok(row.changed>100);assert.equal(row.outside,0,`${row.character}/${row.action} changes outside approved face region`);}fs.writeFileSync(path.join(out,'personality-registration.json'),JSON.stringify(results,null,2));
 }finally{await b.close();s.p.kill();}
});
test('warm and cool expressions survive outfit → action → tabs → photo → save and reopening for all roles',async()=>{
 const s=await server(),b=await chromium.launch({headless:true});try{const p=await b.newPage({viewport:{width:1280,height:720},reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(s.url);await idle(p);const results=[];
  for(const character of ['sweet','cool','literary']){
   await p.locator(`[data-character="${character}"]`).click();await idle(p);await p.locator('#tab-clothes').click();await p.locator('[data-category="shoes"]').click();await p.locator(`[data-item="${character==='cool'?'cool-2026-summer-a-shoes':'shared-shoes-01'}"]`).click();await idle(p);await p.locator('[data-owned]').first().check();const owned=await p.evaluate(()=>JSON.parse(localStorage.getItem('today-outfit-session-v1')).owned);
   for(const light of ['warm','cool']){
    await p.locator('#lighting').click();await p.locator(`[data-light="${light}"]`).click();const action=character==='sweet'?'smile':character==='cool'?'smirk':'knowing';await p.locator(`[data-motion="${action}"]`).click();await p.waitForFunction(id=>document.querySelector('#figure').dataset.motion===id,action);
    await p.locator('#tab-wearing').click();await p.locator('[data-lock="shoes"]').click();await p.locator('#tab-clothes').click();const session=await p.evaluate(()=>localStorage.getItem('today-outfit-session-v1'));
    await p.locator('#photo').click();const match=await p.evaluate(async()=>{const img=document.querySelector('.result-photo');await img.decode();const c=document.createElement('canvas');c.width=900;c.height=1200;const x=c.getContext('2d'),warm=document.querySelector('#stage').dataset.light==='warm',g=x.createRadialGradient(450,350,50,450,450,950);g.addColorStop(0,warm?'#fff5df':'#edf5fa');g.addColorStop(1,warm?'#c9b69c':'#b7c6cf');x.fillStyle=g;x.fillRect(0,0,900,1200);x.fillStyle='#756b5830';x.beginPath();x.ellipse(450,1125,135,17,0,0,Math.PI*2);x.fill();x.drawImage(document.querySelector('#figure'),90,60,720,1080);const a=x.getImageData(0,0,900,1200).data;x.clearRect(0,0,900,1200);x.drawImage(img,0,0);const actual=x.getImageData(0,0,900,1200).data;return a.every((v,i)=>v===actual[i]);});assert.ok(match,'photo must contain the exact local light and expression');await p.locator('#close-dialog').click();
    await p.screenshot({path:path.join(out,`${character}-${light}-face.png`)});const thumbnail=await p.locator('#figure').evaluate(c=>{const t=document.createElement('canvas');t.width=240;t.height=360;t.getContext('2d').drawImage(c,0,0,240,360);return t.toDataURL('image/webp',.8);});await p.locator('#save').click();const name=`局部表情-${character}-${light}`;await p.locator('#plan-name').fill(name);const asCopy=await p.locator('#save-as').count();await p.locator(asCopy?'#save-as':'#confirm-save').click();await p.getByRole('heading',{name:'已保存',exact:true}).waitFor();await p.locator('#close-dialog').click();await p.locator('#library').click();const card=p.locator('.saved-card').filter({has:p.getByRole('heading',{name,exact:true})});assert.equal(await card.locator('img').getAttribute('src'),thumbnail);await card.locator('[data-reopen]').click();await idle(p);await p.waitForFunction(id=>document.querySelector('#figure').dataset.motion===id,action);
    const after=await p.evaluate(()=>localStorage.getItem('today-outfit-session-v1'));assert.deepEqual(JSON.parse(after).roles[character].outfit,JSON.parse(session).roles[character].outfit);assert.deepEqual(JSON.parse(after).roles[character].locks,JSON.parse(session).roles[character].locks);assert.deepEqual(JSON.parse(after).owned,owned);assert.equal(await p.locator('#stage').getAttribute('data-light'),light);await p.locator('[data-motion="neutral"]').click();await p.locator('#tab-wearing').click();await p.locator('[data-lock="shoes"]').click();await p.locator('#tab-clothes').click();results.push({character,light,photoMatches:true,thumbnailMatches:true,reopenPreservesState:true});
   }
  }
  await p.setViewportSize({width:390,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await p.evaluate(()=>document.querySelector('#stage').getBoundingClientRect().bottom<=document.querySelector('.motion-controls').getBoundingClientRect().top));assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'face-light-browser.json'),JSON.stringify({results,mobileWidth:390,errors},null,2));
 }finally{await b.close();s.p.kill();}
});
