const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {chromium}=require('playwright'),{spawn}=require('node:child_process');
const root=path.resolve(__dirname,'..'),out=path.join(root,'output/outfit-eye-check');
const idle=p=>p.waitForFunction(()=>document.querySelector('#stage').getAttribute('aria-busy')==='false'&&!document.querySelector('#save').disabled);
const state=p=>p.evaluate(()=>JSON.parse(localStorage.getItem('today-outfit-session-v1')));
const hash=p=>p.locator('#figure').evaluate(async c=>{const d=c.getContext('2d').getImageData(0,0,1024,1536).data,sha=async a=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',a))).join(',');return {head:await sha(d.slice(0,1024*470*4)),body:await sha(d.slice(1024*470*4))};});
async function server(){fs.mkdirSync(out,{recursive:true});const p=spawn('python3',['-u','serve.py','--port','0'],{cwd:root});const port=await new Promise((ok,no)=>{p.stdout.on('data',b=>{const m=String(b).match(/port (\d+)/);if(m)ok(m[1]);});p.on('error',no);});return {p,url:`http://127.0.0.1:${port}/legacy/index.html`};}
async function outsidePicture(p){const g=await p.evaluate(()=>{const picture=document.querySelector('#stage').getBoundingClientRect();return [...document.querySelectorAll('.motion-controls [data-motion],#motion-note,#status,#retry,#loading,#motion-compatibility')].filter(e=>e.getClientRects().length).map(e=>({id:e.id||e.dataset.motion,top:e.getBoundingClientRect().top,pictureBottom:picture.bottom}));});for(const r of g)assert.ok(r.top>=r.pictureBottom-1,`${r.id} overlays the picture`);}
test('blink retry requests the real eye asset, leaves the outfit intact and keeps errors outside the picture',async()=>{
 const s=await server(),b=await chromium.launch({headless:true});try{const p=await b.newPage({viewport:{width:1280,height:720},reducedMotion:'reduce'});let requests=0;p.on('request',r=>{if(r.url().endsWith('/sweet/blink-detail.png'))requests++;});await p.route('**/sweet/blink-detail.png',r=>r.abort());await p.goto(s.url);await idle(p);assert.equal(requests,1);const before=await hash(p),session=await state(p);
  await p.locator('[data-motion="blink"]').click();await idle(p);assert.equal(requests,2);assert.match(await p.locator('#motion-note').innerText(),/加载失败.*重试/);await outsidePicture(p);assert.deepEqual(await hash(p),before);assert.deepEqual(await state(p),session);await p.screenshot({path:path.join(out,'load-error-safe.png')});
  await p.unroute('**/sweet/blink-detail.png');await p.locator('[data-motion="blink"]').click();await p.waitForFunction(()=>document.querySelector('#figure').dataset.motion==='blink');assert.equal(requests,3);const after=await hash(p);assert.equal(after.body,before.body);assert.notEqual(after.head,before.head);assert.deepEqual(await state(p),session);assert.ok(await p.locator('[data-motion="heart"]').isDisabled());await outsidePicture(p);
  fs.writeFileSync(path.join(out,'load-recovery.json'),JSON.stringify({requests,recovered:true,outfitUnchanged:true,errorOutsidePicture:true},null,2));
 }finally{await b.close();s.p.kill();}
});
test('categories stay visible while only garment content scrolls, with tabs and mobile state retained',async()=>{
 const s=await server(),b=await chromium.launch({headless:true});try{
  for(const viewport of [{width:1280,height:720},{width:390,height:844}]){const p=await b.newPage({viewport,reducedMotion:'reduce'});await p.goto(s.url);await idle(p);await p.locator('[data-owned]').first().check();await p.locator('#tab-wearing').click();await p.locator('[data-lock="bottom"]').click();const before=await state(p);await p.locator('#tab-clothes').click();
   if(viewport.width>760){const top=await p.locator('#categories').evaluate(e=>e.getBoundingClientRect().top);await p.locator('#wardrobe-body').hover();await p.mouse.wheel(0,600);await p.waitForFunction(()=>document.querySelector('#wardrobe-body').scrollTop>100);assert.equal(await p.locator('#categories').evaluate(e=>e.getBoundingClientRect().top),top);assert.equal(await p.locator('#control-content').evaluate(e=>e.scrollTop),0);assert.ok(await p.locator('#categories').isVisible());assert.ok(await p.locator('#save').isVisible());await p.screenshot({path:path.join(out,'categories-scrolled-desktop.png')});}
   else{await p.locator('.preferences summary').scrollIntoViewIfNeeded();const g=await p.locator('#categories').evaluate(e=>{const r=e.getBoundingClientRect();return {top:r.top,bottom:r.bottom};});assert.ok(g.top>=-1&&g.bottom<844);assert.equal(await p.locator('#wardrobe-body').evaluate(e=>getComputedStyle(e).overflowY),'visible');await p.screenshot({path:path.join(out,'categories-scrolled-mobile.png'),fullPage:true});}
   await p.locator('#tab-wearing').click();assert.equal(await p.locator('[data-lock="bottom"]').getAttribute('aria-pressed'),'true');await p.locator('#tab-clothes').click();assert.ok(await p.locator('[data-owned]').first().isChecked());assert.deepEqual(await state(p),before);await outsidePicture(p);await p.close();
  }
 }finally{await b.close();s.p.kill();}
});
test('sweet blink stays registered across four outfits at actual browser zoom, including photo export',async()=>{
 const s=await server(),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'outfit-eye-zoom-')),ext=path.join(tmp,'extension');fs.mkdirSync(ext);
 fs.writeFileSync(path.join(ext,'manifest.json'),JSON.stringify({manifest_version:3,name:'Local zoom verification',version:'1.0',permissions:['tabs'],background:{service_worker:'zoom.js'}}));fs.writeFileSync(path.join(ext,'zoom.js'),'chrome.runtime.onInstalled.addListener(()=>{});');
 const context=await chromium.launchPersistentContext(path.join(tmp,'profile'),{headless:true,channel:'chromium',ignoreDefaultArgs:['--disable-extensions'],args:[`--disable-extensions-except=${ext}`,`--load-extension=${ext}`],viewport:{width:1440,height:1000},reducedMotion:'reduce',acceptDownloads:true});
 try{const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker'),p=await context.newPage(),errors=[],results=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(s.url);try{await idle(p);}catch(e){fs.writeFileSync(path.join(out,'zoom-start-error.json'),JSON.stringify({errors,dom:await p.locator('body').innerText()},null,2));await p.screenshot({path:path.join(out,'zoom-start-error.png')});throw e;}
  const asset=await p.request.get(new URL('../assets/v2/sweet/blink-detail.png',s.url).href);assert.equal(asset.status(),200);assert.ok((await asset.body()).length>20000);
  const fits=[['short-skirt',[['outer','none'],['top','shared-top-04'],['bottom','sweet-bottom-01'],['shoes','sweet-shoes-01'],['bag','none']]],['trousers',[['bottom','shared-bottom-01'],['shoes','shared-shoes-04'],['bag','shared-bag-02']]],['long-coat',[['bottom','sweet-bottom-01'],['outer','sweet-outer-01'],['shoes','sweet-shoes-02'],['bag','sweet-bag-01']]],['dress',[['outer','none'],['dress','sweet-dress-01'],['shoes','shared-shoes-03'],['bag','none']]]];
  let head;for(const [name,changes] of fits){for(const [category,item] of changes){await p.locator(`[data-category="${category}"]`).click();await p.locator(`[data-item="${item}"]`).click();await idle(p);}const before=await hash(p),session=await state(p);if(head)assert.equal(before.head,head);head=before.head;
   for(const zoom of [1,.8,1.25,1.5]){const actual=await worker.evaluate(async ({url,zoom})=>{const t=(await chrome.tabs.query({})).find(t=>t.url===url);await chrome.tabs.setZoom(t.id,zoom);return chrome.tabs.getZoom(t.id);},{url:s.url,zoom});assert.ok(Math.abs(actual-zoom)<.001);await p.waitForTimeout(80);await p.locator('[data-motion="blink"]').click();await p.waitForFunction(()=>document.querySelector('#figure').dataset.motion==='blink');const blink=await hash(p);assert.equal(blink.body,before.body);assert.notEqual(blink.head,before.head);assert.deepEqual(await state(p),session);await outsidePicture(p);
    await p.locator('#photo').click();await p.locator('.result-photo').waitFor();const photo=await p.locator('.result-photo').evaluate(async img=>{await img.decode();return {width:img.naturalWidth,height:img.naturalHeight,src:img.src};});assert.equal(photo.width,900);assert.equal(photo.height,1200);
    const download=p.waitForEvent('download');await p.locator('#photo-download').click();const file=await download;const destination=path.join(out,`${name}-blink-zoom-${zoom}.png`);await file.saveAs(destination);assert.ok(fs.statSync(destination).size>100000);
    const matched=await p.evaluate(async()=>{const c=document.createElement('canvas');c.width=900;c.height=1200;const x=c.getContext('2d'),g=x.createRadialGradient(450,350,50,450,450,950);g.addColorStop(0,'#f5f2eb');g.addColorStop(1,'#dedbd4');x.fillStyle=g;x.fillRect(0,0,900,1200);x.fillStyle='#756b5830';x.beginPath();x.ellipse(450,1125,135,17,0,0,Math.PI*2);x.fill();x.drawImage(document.querySelector('#figure'),90,60,720,1080);const actual=document.createElement('canvas');actual.width=900;actual.height=1200;actual.getContext('2d').drawImage(document.querySelector('.result-photo'),0,0);const a=x.getImageData(0,0,900,1200).data,b=actual.getContext('2d').getImageData(0,0,900,1200).data;return a.every((v,i)=>v===b[i]);});assert.ok(matched,'photo must match current blink and every garment');
    await p.locator('#close-dialog').click();await p.screenshot({path:path.join(out,`${name}-page-zoom-${zoom}.png`)});await p.locator('[data-motion="neutral"]').click();assert.deepEqual(await hash(p),before);results.push({outfit:name,zoom:actual,viewport:await p.evaluate(()=>({width:innerWidth,height:innerHeight,dpr:devicePixelRatio})),bodyUnchanged:true,photoMatched:true});
   }
  }assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'blink-outfits-zoom-photo.json'),JSON.stringify({character:'sweet',results,errors},null,2));
 }finally{await context.close();s.p.kill();fs.rmSync(tmp,{recursive:true,force:true});}
});
