const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs'),{spawn}=require('node:child_process');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),out=path.join(root,'output/guidance-blink-review');
async function server(){const p=spawn('python3',['-u','serve.py','--port','0'],{cwd:root});const port=await new Promise((ok,no)=>{p.stdout.on('data',b=>{const m=String(b).match(/port (\d+)/);if(m)ok(m[1]);});p.on('error',no);});return {p,url:`http://127.0.0.1:${port}/legacy/index.html`};}
const idle=p=>p.waitForFunction(()=>document.querySelector('#stage').getAttribute('aria-busy')==='false'&&!document.querySelector('#save').disabled);
const state=p=>p.evaluate(()=>JSON.parse(localStorage.getItem('today-outfit-session-v1')));
test('recommendation browse returns to clothes from both result and exhaustion without losing outfit, locks or owned choices',async()=>{
 const s=await server(),b=await chromium.launch({headless:true});try{const p=await b.newPage({reducedMotion:'reduce'});await p.goto(s.url);await idle(p);await p.locator('[data-owned]').first().check();await p.locator('#change-need').click();await p.locator('#self-build').click();await idle(p);await p.locator('#tab-wearing').click();await p.locator('[data-lock="bottom"]').click();const before=await state(p);
  await p.locator('#recommend').click();await p.locator('[data-try="0"]:not(:disabled)').waitFor();await p.locator('#browse').click();assert.equal(await p.locator('#tab-clothes').getAttribute('aria-selected'),'true');let after=await state(p);assert.deepEqual(after.roles.sweet.outfit,before.roles.sweet.outfit);assert.deepEqual(after.roles.sweet.locks,before.roles.sweet.locks);assert.deepEqual(after.owned,before.owned);
  await p.locator('.preferences summary').click();await p.locator('#strict-owned').check();await p.locator('#tab-wearing').click();await p.locator('#recommend').click();assert.equal(await p.locator('[data-try]').count(),0);await p.locator('#browse').click();assert.equal(await p.locator('#tab-clothes').getAttribute('aria-selected'),'true');after=await state(p);assert.deepEqual(after.roles.sweet.outfit,before.roles.sweet.outfit);assert.deepEqual(after.roles.sweet.locks,before.roles.sweet.locks);assert.deepEqual(after.owned,before.owned);
 }finally{await b.close();s.p.kill();}
});
test('purpose mismatch is visible while choosing and clears after fixing it; recommendations explain actual suitability',async()=>{
 const s=await server(),b=await chromium.launch({headless:true});try{const p=await b.newPage({viewport:{width:1280,height:720},reducedMotion:'reduce'});await p.goto(s.url);await idle(p);await p.locator('#change-need').click();await p.locator('#get-suggestions').click();await p.locator('[data-try="0"]:not(:disabled)').waitFor();
  const reasons=await p.locator('.suggestion-foot p').allTextContents();assert.equal(reasons.length,3);for(const reason of reasons){assert.match(reason,/上课|学习|书本/);assert.ok(reason.length<65);assert.doesNotMatch(reason,/^上衣 · 下装/);}await p.locator('[data-try="0"]').click();await idle(p);
  await p.locator('[data-category="bag"]').click();await p.locator('[data-item="shared-bag-02"]').click();await idle(p);assert.equal(await p.locator('#tab-clothes').getAttribute('aria-selected'),'true');assert.ok(await p.locator('#fit-note').isVisible());assert.match(await p.locator('#fit-note').innerText(),/上课.*(书本|学习用品)/);await p.locator('#tab-wearing').click();assert.ok(await p.locator('#fit-note').isVisible());await p.locator('#tab-clothes').click();await p.locator('[data-item="shared-bag-01"]').click();await idle(p);assert.equal(await p.locator('#fit-note').isVisible(),false);
  await p.locator('#save').click();await p.locator('[data-alt="top"]').click();const count=await p.locator('[data-alternative]').count();assert.ok(count>2,`expected more than two tops, got ${count}`);assert.equal(count,await p.evaluate(()=>{const s=JSON.parse(localStorage.getItem('today-outfit-session-v1')),r=s.roles.sweet;return OutfitModelV2.itemsFor('sweet').filter(i=>i.slot==='top'&&i.id!==r.outfit.top).filter(i=>{try{OutfitModelV2.change('sweet',r,'top',i.id);return true;}catch(e){return false;}}).length;}));
  await p.locator('[data-alternative]').first().click();await idle(p);await p.locator('#save').click();await p.locator('#plan-name').fill('流程局部修复验收');await p.locator('#confirm-save').click();await p.getByRole('heading',{name:'已保存',exact:true}).waitFor();await p.locator('#close-dialog').click();const saved=(await state(p)).roles.sweet.outfit;await p.locator('[data-character="cool"]').click();await idle(p);await p.locator('#library').click();await p.locator('.saved-card').filter({has:p.getByRole('heading',{name:'流程局部修复验收',exact:true})}).locator('[data-reopen]').click();await idle(p);assert.deepEqual((await state(p)).roles.sweet.outfit,saved);
 }finally{await b.close();s.p.kill();}
});
test('purpose and season are primary; defaults and optional overrides survive editing on desktop and mobile',async()=>{
 const s=await server(),b=await chromium.launch({headless:true});try{fs.mkdirSync(out,{recursive:true});for(const viewport of [{width:1280,height:720},{width:390,height:844}]){const p=await b.newPage({viewport,reducedMotion:'reduce'});await p.goto(s.url);await idle(p);await p.locator('#change-need').click();assert.ok(await p.locator('#season').isVisible());assert.equal(await p.locator('#warmth').isVisible(),false);assert.equal(await p.locator('#walking').isVisible(),false);await p.locator('[data-purpose="shopping"]').click();await p.locator('#season').selectOption('summer');await p.locator('#self-build').click();await idle(p);let n=(await state(p)).need;assert.equal(n.warmth,'hot');assert.equal(n.walking,'normal');assert.match(await p.locator('#need-summary').innerText(),/夏/);
  await p.locator('#change-need').click();await p.locator('#need-options summary').click();await p.locator('#detail').selectOption('street');assert.equal(await p.locator('#walking').inputValue(),'many');await p.locator('#warmth').selectOption('mild');await p.locator('#self-build').click();await idle(p);await p.locator('#change-need').click();await p.locator('#need-options summary').click();assert.equal(await p.locator('#warmth').inputValue(),'mild');assert.equal(await p.locator('#walking').inputValue(),'many');await p.locator('#close-dialog').click();assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:path.join(out,`guidance-${viewport.width}.png`),fullPage:viewport.width<761});await p.close();}
 }finally{await b.close();s.p.kill();}
});
