const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs'),{spawn}=require('node:child_process');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),out=path.join(root,'output/outfit-complete-review');
async function server(){const p=spawn('python3',['-u','-m','http.server','0','--bind','127.0.0.1'],{cwd:root});const port=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('server timeout')),10000);p.stdout.on('data',b=>{const m=String(b).match(/port (\d+)/);if(m){clearTimeout(timer);resolve(m[1]);}});p.on('error',reject);});return {p,url:`http://127.0.0.1:${port}/index.html`};}
const idle=p=>p.waitForFunction(()=>document.querySelector('#stage').getAttribute('aria-busy')==='false');
test('compact desktop controls keep a complete garment row visible through both existing entries',async()=>{
 const s=await server();let browser;try{browser=await chromium.launch({headless:true});
  for(const viewport of [{width:845,height:757},{width:1280,height:720},{width:1440,height:900}]){
   const p=await browser.newPage({viewport}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(s.url);await idle(p);
   const geometry=()=>p.evaluate(()=>{const rect=e=>{const r=e.getBoundingClientRect();return {top:r.top,bottom:r.bottom,left:r.left,width:r.width,height:r.height};},controls=rect(document.querySelector('.controls')),items=rect(document.querySelector('#control-content')),bar=rect(document.querySelector('.action-bar'));return {stage:rect(document.querySelector('#stage')),characters:rect(document.querySelector('#characters')),row:[...document.querySelectorAll('.item-card')].slice(0,3).map(rect),top:Math.max(0,controls.top,items.top),bottom:Math.min(innerHeight,controls.bottom,items.bottom,bar.top),scroll:scrollY};});
   const visibleRow=async()=>{const g=await geometry();assert.equal(g.row.length,3);for(const card of g.row){assert.ok(card.top>=g.top-1,'the whole card must start inside the wardrobe');assert.ok(card.bottom<=g.bottom+1,`card bottom ${card.bottom} must be above clipping or sticky actions at ${g.bottom}`);}return g;};
   const initial=await visibleRow(),figure=await p.locator('#figure').getAttribute('aria-label');assert.equal(await p.locator('#tab-clothes').getAttribute('aria-selected'),'true');assert.equal(await p.locator('#need-summary').isVisible(),true);
   const layoutOut=path.join(root,'output/outfit-controls-layout');fs.mkdirSync(layoutOut,{recursive:true});if(viewport.width===845)await p.screenshot({path:path.join(layoutOut,'current-window-entry.png')});
   await p.locator('#free').click();await p.locator('#items').evaluate(el=>new Promise(resolve=>{let previous,stable=0;function settled(){const position=scrollY+'|'+el.closest('.controls').scrollTop;stable=position===previous?stable+1:0;previous=position;if(stable>=12)resolve();else requestAnimationFrame(settled);}requestAnimationFrame(settled);}));const browsing=await visibleRow();assert.deepEqual(browsing.stage,initial.stage);assert.deepEqual(browsing.characters,initial.characters);assert.equal(await p.locator('#figure').getAttribute('aria-label'),figure);if(viewport.width===845)await p.screenshot({path:path.join(layoutOut,'current-window-wardrobe.png')});
   for(const character of ['cool','literary','sweet']){await p.locator(`[data-character="${character}"]`).click();await idle(p);await visibleRow();}
   await p.locator('#recommend').click();await p.locator('#get-suggestions').click();await p.locator('[data-try="0"]:not(:disabled)').waitFor();await p.locator('[data-try="0"]').click();await idle(p);await visibleRow();assert.equal(await p.locator('#panel-wearing').isVisible(),false);assert.equal(await p.locator('#need-summary').isVisible(),true);if(viewport.width===845)await p.screenshot({path:path.join(layoutOut,'current-window-recommendation.png')});
   await p.locator('#change-need').click();await p.locator('[data-purpose="date"]').click();await p.locator('#self-build').click();await idle(p);await visibleRow();assert.match(await p.locator('#purpose-title').innerText(),/约会/);
   await p.locator('#tab-clothes').click();await p.locator('[data-category="shoes"]').click();await p.locator('[data-item]:not([aria-pressed="true"]):not(:disabled)').first().click();await idle(p);await visibleRow();assert.deepEqual(errors,[]);await p.close();
  }
 }finally{await browser?.close();s.p.kill();}
});
async function seedTrip(p,pending=false){await p.evaluate(async pending=>{const M=OutfitModelV2,T=OutfitTravelV2,N=PlannerNeeds,s=M.createState(),need=N.normalizeNeed({activity:'short-trip',days:2,season:'spring',warmth:'mild'});s.need=need;let trip=T.create('sweet',need,2);trip.days[0].locks={shoes:'shared-shoes-01'};trip.noReuseItems=['shared-shoes-01'];trip=T.generate(trip);if(pending){trip.days[1].outfit=null;trip.days[1].reason='等待安排';trip.days[1].locks={};}const r=M.recordTrip(s,trip,{id:'regression-trip',name:'回归行程'});await OutfitStorageV2.createRepository().save(r);},pending);await p.locator('#library').click();await p.locator('[data-reopen="regression-trip"]').click();await idle(p);}
test('a pending day never inherits the previous days locks',async()=>{
 const s=await server();let b;try{b=await chromium.launch({headless:true});const p=await b.newPage();await p.goto(s.url);await idle(p);await seedTrip(p,true);await p.locator('[data-day="1"]').click();await idle(p);await p.locator('#tab-wearing').click();assert.equal(await p.locator('[data-lock="shoes"]').getAttribute('aria-pressed'),'false');assert.deepEqual(await p.evaluate(()=>JSON.parse(localStorage.getItem('today-outfit-session-v1')).roles.sweet.locks),{});}finally{await b?.close();s.p.kill();}
});
test('day recommendation excludes non-reusable pieces worn on another day',async()=>{
 const s=await server();let b;try{b=await chromium.launch({headless:true});const p=await b.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(s.url);await idle(p);await seedTrip(p);await p.locator('[data-day="1"]').click();await idle(p);await p.locator('#recommend').click();await p.locator('[data-try="0"]:not(:disabled)').waitFor();await p.locator('[data-try="0"]').click();await p.waitForTimeout(250);await idle(p);assert.deepEqual(errors,[]);assert.equal(await p.locator('#dialog').evaluate(d=>d.open),false);assert.notEqual(await p.evaluate(()=>JSON.parse(localStorage.getItem('today-outfit-session-v1')).trip.days[1].outfit.shoes),'shared-shoes-01');}finally{await b?.close();s.p.kill();}
});
test('closing the need form cancels its pending preparation and cannot reopen a dialog',async()=>{
 const s=await server();let b,finish;try{b=await chromium.launch({headless:true});const p=await b.newPage();await p.goto(s.url);await idle(p);await p.waitForFunction(()=>!document.querySelector('#save').disabled);const baseline=await p.evaluate(()=>({session:localStorage.getItem('today-outfit-session-v1'),figure:document.querySelector('#figure').getAttribute('aria-label')}));let announce;const reached=new Promise(resolve=>announce=resolve);await p.route('**/assets/v2/sweet/*.webp',async r=>{if(!finish){await new Promise(resolve=>{finish=resolve;announce();});}await r.continue();});await p.locator('#change-need').click();await p.locator('[data-purpose=\"short-trip\"]').click();await p.locator('#get-suggestions').click();await p.waitForFunction(()=>document.querySelector('#stage').getAttribute('aria-busy')==='true');await reached;await p.locator('#close-dialog').click();assert.ok(finish,'the new outfit must be waiting on a real garment');finish();await idle(p);assert.equal(await p.locator('#dialog').evaluate(d=>d.open),false);assert.deepEqual(await p.evaluate(()=>({session:localStorage.getItem('today-outfit-session-v1'),figure:document.querySelector('#figure').getAttribute('aria-label')})),baseline);}finally{finish?.();await b?.close();s.p.kill();}
});
test('a pending scene cannot export the previous scene under a new background selection',async()=>{
 const s=await server();let browser;try{browser=await chromium.launch({headless:true});const p=await browser.newPage();await p.goto(s.url);await idle(p);await p.locator('#background').click();await p.locator('[data-background="city"]').click();await p.waitForFunction(()=>!document.querySelector('#scene').hidden);let finish;await p.route('**/scenes/walk.webp',async r=>{await new Promise(resolve=>finish=resolve);await r.continue();});await p.locator('#background').click();await p.locator('[data-background="walk"]').click();await p.waitForFunction(()=>document.querySelector('#stage').dataset.background==='walk');assert.equal(await p.locator('#photo').isDisabled(),true);finish();await p.waitForFunction(()=>!document.querySelector('#scene').hidden&&document.querySelector('#scene').src.includes('walk.webp'));assert.equal(await p.locator('#photo').isEnabled(),true);}finally{await browser?.close();s.p.kill();}
});
test('complete preview supports the practical single-day and three-day workflows',async()=>{
 fs.mkdirSync(out,{recursive:true});const s=await server();let browser;try{browser=await chromium.launch({headless:true});const p=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>localStorage.setItem('studio-wardrobe-planner-v1','sentinel'));await p.goto(s.url);await idle(p);assert.equal(await p.locator('[data-character]').count(),3);
 await p.screenshot({path:path.join(out,'complete-start.png')});
 await p.locator('#change-need').click();await p.locator('[data-purpose=\"class\"]').click();await p.locator('#get-suggestions').click();await p.locator('[data-try="0"]:not(:disabled)').waitFor();assert.equal(await p.locator('[data-try]').count(),3);await p.screenshot({path:path.join(out,'complete-suggestions.png')});await p.locator('[data-try="0"]').click();await idle(p);
 const bottom=await p.evaluate(()=>JSON.parse(localStorage.getItem('today-outfit-session-v1')).roles.sweet.outfit.bottom);await p.locator('#tab-wearing').click();await p.locator('[data-lock="bottom"]').click();await p.locator('#remix').click();await p.locator('[data-try="0"]:not(:disabled)').waitFor();await p.locator('[data-try="0"]').click();await idle(p);assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('today-outfit-session-v1')).roles.sweet.outfit.bottom),bottom);
 await p.locator('#tab-clothes').click();await p.locator('[data-category="shoes"]').click();await p.locator('[data-item]:not([aria-pressed="true"]):not(:disabled)').first().click();await idle(p);await p.locator('#save').click();await p.locator('#plan-name').fill('上课验收');await p.locator('#confirm-save').click();await p.getByRole('heading',{name:'已保存',exact:true}).waitFor();await p.locator('#close-dialog').click();
 await p.locator('[data-character="cool"]').click();await idle(p);await p.locator('#library').click();await p.locator('[data-reopen]').first().click();await idle(p);assert.ok((await p.locator('#figure').getAttribute('aria-label')).startsWith('吴心媛'));await p.locator('#tab-wearing').click();assert.equal(await p.locator('[data-lock="bottom"]').getAttribute('aria-pressed'),'true');await p.locator('#save').click();assert.equal(await p.locator('#confirm-save').innerText(),'更新此方案');await p.locator('#confirm-save').click();await p.getByRole('heading',{name:'已保存',exact:true}).waitFor();await p.locator('#close-dialog').click();await p.locator('#save').click();await p.locator('#plan-name').fill('另存验收');await p.locator('#save-as').click();await p.getByRole('heading',{name:'已保存',exact:true}).waitFor();await p.locator('#close-dialog').click();await p.locator('#library').click();await p.locator('[data-reopen]').nth(1).waitFor();assert.equal(await p.locator('[data-reopen]').count(),2);await p.locator('#close-dialog').click();
 await p.locator('[data-character="literary"]').click();await idle(p);await p.locator('#tab-clothes').click();await p.locator('[data-category="dress"]').click();await p.locator('[data-item="literary-dress-01"]').click();await idle(p);assert.ok((await p.locator('#figure').getAttribute('aria-label')).includes('背带裙'));await p.locator('[data-item="none"]').click();await idle(p);assert.ok(!(await p.locator('#figure').getAttribute('aria-label')).includes('背带裙'));
 await p.locator('#change-need').click();await p.locator('[data-purpose="short-trip"]').click();await p.locator('#duration').selectOption('3');await p.locator('#get-suggestions').click();await p.getByRole('heading',{name:'逐日搭配',exact:true}).waitFor();assert.equal(await p.locator('[data-edit-trip]').count(),3);await p.screenshot({path:path.join(out,'complete-trip.png')});await p.locator('[data-edit-trip="1"]').click();await idle(p);await p.locator('#edit-day').click();await p.locator('[data-purpose="date"]').click();await p.locator('#get-suggestions').click();await p.locator('[data-try="0"]:not(:disabled)').waitFor();await p.locator('[data-try="0"]').click();await idle(p);await p.locator('#tab-wearing').click();await p.locator('[data-lock="shoes"]').click();const d2=await p.evaluate(()=>JSON.parse(localStorage.getItem('today-outfit-session-v1')).trip.days[1]);await p.locator('[data-day="0"]').click();await idle(p);await p.locator('#tab-wearing').click();assert.equal(await p.locator('[data-lock="shoes"]').getAttribute('aria-pressed'),'false');await p.locator('#trip-overview').click();await p.locator('#regenerate-trip').click();await p.getByRole('heading',{name:'逐日搭配',exact:true}).waitFor();await idle(p);const kept=await p.evaluate(()=>JSON.parse(localStorage.getItem('today-outfit-session-v1')).trip.days[1]);assert.equal(kept.outfit.shoes,d2.outfit.shoes);await p.locator('#packing').click();await p.locator('[data-quantity]').first().fill('2');await p.locator('[data-quantity]').first().dispatchEvent('change');assert.ok((await p.locator('#dialog-body').innerText()).includes('首日穿1件'));await p.screenshot({path:path.join(out,'complete-packing.png')});await p.locator('#save-trip').click();await p.locator('#plan-name').fill('三日旅行验收');await p.locator('#confirm-save').click();await p.getByRole('heading',{name:'已保存',exact:true}).waitFor();await p.locator('#close-dialog').click();await p.locator('#exit-trip').click();await idle(p);await p.locator('#library').click();await p.locator('.saved-card').filter({has:p.getByRole('heading',{name:'三日旅行验收',exact:true})}).locator('[data-reopen]').click();await idle(p);assert.equal(await p.locator('[data-day]').count(),3);assert.equal(await p.evaluate(()=>Object.values(JSON.parse(localStorage.getItem('today-outfit-session-v1')).trip.quantities)[0]),2);
 await p.locator('#lighting').click();await p.locator('[data-light="warm"]').click();assert.equal(await p.locator('#stage').getAttribute('data-light'),'warm');await p.locator('#photo').click();await p.locator('.result-photo').waitFor();const download=p.waitForEvent('download');await p.locator('#photo-download').click();await (await download).saveAs(path.join(out,'complete-clean-photo.png'));await p.locator('#close-dialog').click();await p.screenshot({path:path.join(out,'complete-desktop.png')});for(const width of [820,390]){await p.setViewportSize({width,height:844});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.screenshot({path:path.join(out,`complete-${width}.png`),fullPage:true});}assert.equal(await p.evaluate(()=>localStorage.getItem('studio-wardrobe-planner-v1')),'sentinel');assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'complete-browser.json'),JSON.stringify({singleDay:true,tripDays:3,saveUpdateCopyReopen:true,quantity:2,photoDownload:true,viewportWidths:[1440,820,390],errors},null,2));
 }finally{await browser?.close();s.p.kill();}
});

test('failed garment preparation retains the current outfit and supports an explicit retry',async()=>{
 const s=await server();let b;try{b=await chromium.launch({headless:true});const p=await b.newPage();await p.goto(s.url);await idle(p);const before=await p.evaluate(()=>JSON.parse(localStorage.getItem('today-outfit-session-v1')).roles.sweet.outfit);let failed=false;await p.route('**/sweet/shared-top-04.webp',r=>{if(!failed){failed=true;return r.abort();}return r.continue();});await p.locator('[data-item="shared-top-04"]').click();await idle(p);assert.deepEqual(await p.evaluate(()=>JSON.parse(localStorage.getItem('today-outfit-session-v1')).roles.sweet.outfit),before);await p.locator('#retry').click();await idle(p);assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('today-outfit-session-v1')).roles.sweet.outfit.top),'shared-top-04');}finally{await b?.close();s.p.kill();}
});
test('strict owned exhaustion is honest and unavailable storage still allows a useful checklist download',async()=>{
 const s=await server();let b;try{b=await chromium.launch({headless:true});const p=await b.newPage();await p.addInitScript(()=>Object.defineProperty(window,'indexedDB',{value:undefined}));await p.goto(s.url);await idle(p);await p.locator('.preferences summary').click();await p.locator('#strict-owned').check();await p.locator('#change-need').click();await p.locator('[data-purpose=\"class\"]').click();await p.locator('#get-suggestions').click();await p.getByRole('heading',{name:'搭配建议',exact:true}).waitFor();assert.equal(await p.locator('[data-try]').count(),0);assert.match(await p.locator('#dialog-body').innerText(),/类似|单品|衣橱/);await p.locator('#close-dialog').click();await p.locator('#save').click();await p.locator('#confirm-save').click();await p.locator('#save-error:not([hidden])').waitFor();const d=p.waitForEvent('download');await p.locator('#download-list').click();assert.equal((await d).suggestedFilename(),'穿搭清单.txt');assert.ok(await p.locator('#figure').isVisible());}finally{await b?.close();s.p.kill();}
});
test('trial only records viewing and explicit adoption changes the adopted history',async()=>{
 const s=await server();let b;try{b=await chromium.launch({headless:true});const p=await b.newPage();await p.goto(s.url);await idle(p);await p.locator('#change-need').click();await p.locator('[data-purpose=\"class\"]').click();await p.locator('#get-suggestions').click();await p.locator('[data-try="0"]:not(:disabled)').waitFor();await p.locator('[data-try="0"]').click();await idle(p);assert.deepEqual(await p.evaluate(()=>JSON.parse(localStorage.getItem('today-outfit-session-v1')).adopted),[]);assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('today-outfit-session-v1')).tried.length),1);await p.locator('#save').click();await p.locator('#confirm-save').click();await p.locator('#wear-today').click();assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('today-outfit-session-v1')).adopted.length),1);}finally{await b?.close();s.p.kill();}
});
test('trip reuse controls reevaluate all days and duration can be resized seven to one',async()=>{
 const s=await server();let b;try{b=await chromium.launch({headless:true});const p=await b.newPage();await p.goto(s.url);await idle(p);await seedTrip(p);await p.locator('#trip-overview').click();await p.locator('#dialog details summary').click();await p.locator('[data-shared="shoes"]').check();await idle(p);await p.locator('[data-edit-trip="1"]').waitFor();const t=await p.evaluate(()=>JSON.parse(localStorage.getItem('today-outfit-session-v1')).trip);assert.equal(t.days[1].outfit,null);assert.match(t.days[1].reason,/复用|锁定/);await p.locator('#trip-duration').selectOption('7');await idle(p);await p.locator('[data-edit-trip="6"]').waitFor();await p.locator('#trip-duration').selectOption('1');await idle(p);assert.equal(await p.locator('[data-edit-trip]').count(),1);assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('today-outfit-session-v1')).trip.days.length),1);}finally{await b?.close();s.p.kill();}
});
test('a malformed stored trip does not hide valid saved outfits or its raw export',async()=>{
 const s=await server();let b;try{b=await chromium.launch({headless:true});const p=await b.newPage();await p.goto(s.url);await idle(p);await p.evaluate(async()=>{const good=OutfitModelV2.record(OutfitModelV2.createState(),{id:'good',name:'正常搭配'});await OutfitStorageV2.createRepository().save(good);const db=await new Promise((ok,no)=>{const r=indexedDB.open(OutfitStorageV2.DATABASE,1);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error);});await new Promise((ok,no)=>{const tx=db.transaction('plans','readwrite');tx.objectStore('plans').put({...good,id:'bad',name:'损坏行程',kind:'trip',trip:{character:'sweet',days:[null]}});tx.oncomplete=ok;tx.onerror=no;});db.close();});await p.locator('#library').click();await p.locator('[data-reopen="good"]').waitFor();await p.locator('[data-export="bad"]').waitFor();assert.equal(await p.locator('.saved-card').count(),2);const d=p.waitForEvent('download');await p.locator('[data-export="bad"]').click();assert.equal((await d).suggestedFilename(),'原方案.json');}finally{await b?.close();s.p.kill();}
});
