const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{spawn}=require('node:child_process');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),out=path.join(root,'output/guidance-blink-review');
async function server(){const p=spawn('python3',['-u','serve.py','--port','0'],{cwd:root});const port=await new Promise((ok,no)=>{p.stdout.on('data',b=>{const m=String(b).match(/port (\d+)/);if(m)ok(m[1]);});p.on('error',no);});return {p,url:`http://127.0.0.1:${port}/legacy/index.html`};}
const idle=p=>p.waitForFunction(()=>document.querySelector('#stage').getAttribute('aria-busy')==='false'&&!document.querySelector('#save').disabled);
test('all registered blink phases change only the eyes across new cool looks and other characters outfits',async()=>{
 const s=await server(),b=await chromium.launch({headless:true});try{const p=await b.newPage({reducedMotion:'reduce'});await p.goto(s.url);await idle(p);const result=await p.evaluate(async()=>{
  const renderer=OutfitRendererV2.createRenderer(),M=OutfitModelV2,result=[],eyes={sweet:[[438,293,58,40],[562,293,60,40]],cool:[[440,285,57,40],[570,275,60,41]],literary:[[431,320,62,48],[556,306,62,46]]};
  for(const character of ['sweet','cool','literary']){const base=M.defaultOutfit(character),outfits=character==='cool'?M.looksFor('cool').map(l=>l.outfit):[base,{...base,top:'shared-top-04',bottom:'shared-bottom-01',dress:null,shoes:'shared-shoes-04'},{...base,outer:character==='sweet'?'sweet-outer-01':'literary-outer-02'}];let expectedHead;
   for(const outfit of outfits){const prepared=await renderer.compose({character,outfit}),before=prepared.figure.getContext('2d').getImageData(0,0,1024,1536).data,head=Array.from(before.slice(0,1024*(character==='cool'?385:435)*4));if(expectedHead&&head.some((v,i)=>v!==expectedHead[i]))throw Error(character+' head moved between garments');expectedHead=head;
    for(const closure of [0,.5,1]){const motion=await OutfitMotionsV2.frame(prepared,'blink',closure),after=motion.figure.getContext('2d').getImageData(0,0,1024,1536).data;let changed=0,outside=0;for(let y=0;y<1536;y++)for(let x=0;x<1024;x++){const k=(y*1024+x)*4;if([0,1,2,3].some(i=>before[k+i]!==after[k+i])){changed++;if(!eyes[character].some(([cx,cy,rx,ry])=>((x-cx)/(rx+1))**2+((y-cy)/(ry+1))**2<=1.02))outside++;}}result.push({character,closure,changed,outside});}
   }
  }return result;
 });for(const row of result){assert.equal(row.outside,0,`${row.character}/${row.closure} changes outside registered eyes`);assert.ok(row.closure===0?row.changed===0:row.changed>500);}fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'blink-registration.json'),JSON.stringify(result,null,2));
 }finally{await b.close();s.p.kill();}
});
test('normal-motion blink closes and opens in one short cycle, pauses for the exact photo and never mutates outfit state',async()=>{
 const s=await server(),b=await chromium.launch({headless:true});try{const p=await b.newPage({viewport:{width:1280,height:720},reducedMotion:'no-preference'});await p.goto(s.url);await idle(p);await p.clock.install();await p.clock.pauseAt(new Date(Date.now()+100));const session=await p.evaluate(()=>localStorage.getItem('today-outfit-session-v1'));await p.locator('button[data-motion="blink"]').click();await p.waitForFunction(()=>document.querySelector('#figure').dataset.motion==='blink');
  const steps=[];for(const ms of [34,34,34]){await p.clock.runFor(ms);steps.push(await p.locator('#figure').getAttribute('data-blink-step'));}assert.ok(steps.includes('1'));assert.ok(steps.includes('2'));
  fs.mkdirSync(out,{recursive:true});await p.screenshot({path:path.join(out,'blink-closed-desktop.png')});await p.locator('#photo').click();await p.clock.runFor(500);const matched=await p.evaluate(async()=>{const img=document.querySelector('.result-photo');await img.decode();const c=document.createElement('canvas');c.width=900;c.height=1200;const x=c.getContext('2d'),g=x.createRadialGradient(450,350,50,450,450,950);g.addColorStop(0,'#f5f2eb');g.addColorStop(1,'#dedbd4');x.fillStyle=g;x.fillRect(0,0,900,1200);x.fillStyle='#756b5830';x.beginPath();x.ellipse(450,1125,135,17,0,0,Math.PI*2);x.fill();x.drawImage(document.querySelector('#figure'),90,60,720,1080);const actual=document.createElement('canvas');actual.width=900;actual.height=1200;actual.getContext('2d').drawImage(img,0,0);const a=x.getImageData(0,0,900,1200).data,v=actual.getContext('2d').getImageData(0,0,900,1200).data;return a.every((n,i)=>n===v[i]);});assert.ok(matched);await p.locator('#close-dialog').click();await p.clock.runFor(230);assert.equal(await p.locator('#figure').getAttribute('data-motion'),'neutral');assert.equal(await p.evaluate(()=>localStorage.getItem('today-outfit-session-v1')),session);
  // A clothing change interrupts the eye cycle; an old callback cannot repaint it.
  await p.locator('button[data-motion="blink"]').click();await p.clock.runFor(60);await p.locator('[data-item="shared-top-04"]').click();await idle(p);await p.clock.runFor(400);assert.equal(await p.locator('#figure').getAttribute('data-motion'),'neutral');assert.match(await p.locator('#figure').getAttribute('aria-label'),/基础棉衬衫/);
 }finally{await b.close();s.p.kill();}
});
