const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.argv[3]||path.join(root,'output/release'));
const url=process.argv[2]||'http://127.0.0.1:8876/',SESSION='today-outfit-session-v1';
const idle=p=>p.waitForFunction(()=>document.querySelector('#stage')?.getAttribute('aria-busy')==='false'&&!document.querySelector('#save').disabled,{},{timeout:45000});
const session=p=>p.evaluate(key=>JSON.parse(localStorage.getItem(key)),SESSION);
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true});try{
 const p=await b.newPage({viewport:{width:1280,height:900},reducedMotion:'reduce',acceptDownloads:true}),errors=[],bad=[],results=[];
 p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)bad.push({url:r.url(),status:r.status()});});p.on('requestfailed',r=>bad.push({url:r.url(),error:r.failure()?.errorText}));
 const response=await p.goto(url,{waitUntil:'networkidle',timeout:60000});assert.equal(response.status(),200);await idle(p);assert.match(await p.title(),/穿搭与旅行衣橱/);
 // Every runtime asset is available from the published project subdirectory.
 const base=new URL('./',url),files=Object.keys(JSON.parse(fs.readFileSync(path.join(root,'runtime-manifest.json'))));
 for(let i=0;i<files.length;i+=3)await Promise.all(files.slice(i,i+3).map(async f=>{const r=await p.request.head(new URL(f,base).href);assert.equal(r.status(),200,f);}));
 for(const role of ['sweet','cool','literary']){
  await p.locator(`[data-character="${role}"]`).click();await idle(p);await p.locator('#free').click();await p.locator('[data-category="top"]').click();const top=role==='cool'?'cool-2026-spring-b-top':'shared-top-04';await p.locator(`[data-item="${top}"]`).click();await idle(p);await p.locator(`[data-owned="${top}"]`).check();await p.locator('[data-category="shoes"]').click();await p.locator(`[data-item="${role==='cool'?'cool-2026-autumn-a-shoes':'shared-shoes-04'}"]`).click();await idle(p);
  const before=await session(p),body=await p.locator('#figure').evaluate(c=>c.getContext('2d').getImageData(0,470,1024,1066).data.toString());
  await p.locator('[data-motion="blink"]').click();await p.waitForFunction(()=>document.querySelector('#figure').dataset.motion==='blink');assert.equal(await p.locator('#figure').evaluate(c=>c.getContext('2d').getImageData(0,470,1024,1066).data.toString()),body);
  await p.locator('#tab-wearing').click();await p.locator('[data-lock="shoes"]').click();await p.locator('#tab-clothes').click();assert.deepEqual((await session(p)).roles[role].outfit,before.roles[role].outfit);
  await p.locator('#save').click();await p.locator('#plan-name').fill(`上线核对-${role}`);await p.locator('#confirm-save').click();await p.getByRole('heading',{name:'已保存',exact:true}).waitFor();await p.locator('#close-dialog').click();await p.locator('#library').click();const card=p.locator('.saved-card').filter({has:p.getByRole('heading',{name:`上线核对-${role}`,exact:true})});await card.waitFor();assert.ok(await card.locator('img').isVisible());await card.locator('[data-reopen]').click();await idle(p);assert.deepEqual((await session(p)).roles[role].outfit,before.roles[role].outfit);results.push({role,garments:true,blink:true,tabs:true,saveReopen:true});
  await p.locator('#tab-wearing').click();await p.locator('[data-lock="shoes"]').click();await p.locator('#tab-clothes').click();await p.locator('[data-motion="neutral"]').click();
 }
 await p.locator('#change-need').click();await p.locator('[data-purpose="class"]').click();await p.locator('#get-suggestions').click();await p.locator('[data-try="0"]:not(:disabled)').waitFor();await p.locator('[data-try="0"]').click();await idle(p);
 assert.equal(await p.locator('#stage').getAttribute('data-background'),'studio');assert.equal(await p.locator('#background').count(),0);await p.locator('#toggle-controls').click();assert.equal(await p.locator('#outfit-controls').isVisible(),false);await p.locator('#toggle-controls').click();assert.equal(await p.locator('#outfit-controls').isVisible(),true);
 await p.locator('#photo').click();const image=p.locator('.result-photo');await image.waitFor();assert.deepEqual(await image.evaluate(async i=>{await i.decode();return [i.naturalWidth,i.naturalHeight];}),[900,1200]);const download=p.waitForEvent('download');await p.locator('#photo-download').click();await(await download).saveAs(path.join(out,'public-photo.png'));await p.locator('#close-dialog').click();
 await p.locator('#change-need').click();await p.locator('[data-purpose="short-trip"]').click();await p.locator('#duration').selectOption('3');await p.locator('#get-suggestions').click();await p.locator('[data-edit-trip="0"]').waitFor();assert.equal(await p.locator('[data-edit-trip]').count(),3);await p.locator('#packing').click();assert.ok(await p.locator('[data-quantity]').count());await p.locator('#save-trip').click();await p.locator('#plan-name').fill('上线核对-三日旅行');await p.locator('#confirm-save').click();await p.getByRole('heading',{name:'已保存',exact:true}).waitFor();await p.locator('#close-dialog').click();await p.locator('#exit-trip').click();await idle(p);await p.locator('#library').click();await p.locator('.saved-card').filter({has:p.getByRole('heading',{name:'上线核对-三日旅行',exact:true})}).locator('[data-reopen]').click();await idle(p);assert.equal(await p.locator('[data-day]').count(),3);await p.reload();await idle(p);await p.locator('#library').click();await p.locator('.saved-card').first().waitFor();assert.equal(await p.locator('.saved-card').count(),4);await p.locator('#close-dialog').click();
 await p.locator('[data-character="sweet"]').click();await idle(p);await p.locator('#free').click();await p.locator('[data-category="top"]').click();await p.locator('#wardrobe-body').hover();await p.mouse.wheel(0,450);await p.waitForFunction(()=>document.querySelector('#wardrobe-body').scrollTop>0);await p.screenshot({path:path.join(out,'public-desktop.png')});
 await p.setViewportSize({width:390,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const mobile=[];for(const role of ['sweet','cool','literary']){await p.locator(`[data-character="${role}"]`).click();await idle(p);await p.locator('#tab-clothes').click();await p.locator('[data-category="shoes"]').click();const shoe=role==='cool'?'cool-2026-summer-a-shoes':'shared-shoes-01';await p.locator(`[data-item="${shoe}"]`).click();await idle(p);assert.equal((await session(p)).roles[role].outfit.shoes,shoe);await p.locator('[data-motion="blink"]').click();await p.waitForFunction(()=>document.querySelector('#figure').dataset.motion==='blink');await p.locator('[data-motion="neutral"]').click();assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));mobile.push({role,garment:true,blink:true});}await p.locator('[data-character="sweet"]').click();await idle(p);await p.locator('[data-category="top"]').click();await p.screenshot({path:path.join(out,'public-mobile.png'),fullPage:true});assert.deepEqual(errors,[]);assert.deepEqual(bad,[]);
 const result={url,runtimeFiles:files.length,roles:results,recommendations:true,tripDays:3,packing:true,photoDownload:true,reloadLibrary:true,desktop:true,mobileViewport:true,mobileRoles:mobile,errors,bad};fs.writeFileSync(path.join(out,'smoke-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
 }finally{await b.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
